from __future__ import annotations

import re

COLLABORATION_SESSION_ID_BYTES = 12
COLLABORATION_SESSION_TOKEN_BYTES = 24
COLLABORATION_CLIENT_ID_BYTES = 8
COLLABORATION_MAX_ACTIVE_SESSIONS = 64
COLLABORATION_IDLE_TTL_MS = 6 * 60 * 60 * 1000
COLLABORATION_MAX_EVENTS_PER_SESSION = 16
COLLABORATION_MAX_PEERS_PER_SESSION = 32
COLLABORATION_EVENT_TYPE_MAX_CHARS = 64
COLLABORATION_CLIENT_ID_MAX_CHARS = 96
COLLABORATION_LABEL_MAX_CHARS = 120
COLLABORATION_EVENT_PAYLOAD_MAX_BYTES = 1024 * 1024
COLLABORATION_BROADCAST_PEER_TIMEOUT_MS = 20
COLLABORATION_MS_PER_SECOND = 1000
COLLABORATION_BROADCAST_PEER_TIMEOUT_SECONDS = (
    COLLABORATION_BROADCAST_PEER_TIMEOUT_MS / COLLABORATION_MS_PER_SECOND
)
COLLABORATION_JOURNAL_PATH_ENV = "URDF_COLLABORATION_JOURNAL_PATH"
COLLABORATION_JOURNAL_SCHEMA_VERSION = 1
COLLABORATION_JOURNAL_WRITE_FILE_MODE = 0o600
COLLABORATION_JOURNAL_TOKEN_DIGEST_PREFIX = "sha256:"
COLLABORATION_JOURNAL_EVENT_SESSION_CREATED = "session.created"
COLLABORATION_JOURNAL_EVENT_ACCESS_UPDATED = "access.updated"
COLLABORATION_ACCESS_PAUSED_MESSAGE = (
    "The owner temporarily stopped sharing this session."
)
COLLABORATION_ACCESS_REVOKED_MESSAGE = "You are no longer part of this sharing session."
COLLABORATION_SESSION_ENDED_MESSAGE = "This sharing session is no longer live."
COLLABORATION_JOURNAL_EVENT_COLLABORATION_EVENT_ACCEPTED = "event.accepted"
COLLABORATION_WEBSOCKET_UNAUTHORIZED_CLOSE_CODE = 4401
COLLABORATION_WEBSOCKET_CAPACITY_CLOSE_CODE = 4429
COLLABORATION_WEBSOCKET_ACCESS_REVOKED_CLOSE_CODE = 4403
COLLABORATION_WEBSOCKET_ACCESS_REVOKED_REASON = "Collaboration editor access revoked."
COLLABORATION_INITIAL_EVENT_ID = 1
COLLABORATION_CLIENT_SEQUENCE_FIELD = "clientSequence"
COLLABORATION_CLIENT_SEQUENCE_MIN = 0
COLLABORATION_CLIENT_SEQUENCE_MAX = 9_007_199_254_740_991
COLLABORATION_COUNTER_INCREMENT = 1
COLLABORATION_SESSION_TOKEN_HEADER = "X-URDF-Collaboration-Token"
COLLABORATION_CLIENT_ID_QUERY_PARAM = "client_id"
COLLABORATION_WEBSOCKET_PROTOCOL = "urdf-collab"
COLLABORATION_WEBSOCKET_TOKEN_PROTOCOL_PREFIX = "urdf-collab-token-"
COLLABORATION_EVENT_TYPE_TRAILING_CHARS = COLLABORATION_EVENT_TYPE_MAX_CHARS - 1
COLLABORATION_CLIENT_ID_TRAILING_CHARS = COLLABORATION_CLIENT_ID_MAX_CHARS - 1
COLLABORATION_EVENT_TYPE_PATTERN = re.compile(
    rf"^[A-Za-z][A-Za-z0-9._:-]{{0,{COLLABORATION_EVENT_TYPE_TRAILING_CHARS}}}$"
)
COLLABORATION_CLIENT_ID_PATTERN = re.compile(
    rf"^[A-Za-z0-9][A-Za-z0-9._:-]{{0,{COLLABORATION_CLIENT_ID_TRAILING_CHARS}}}$"
)
