from __future__ import annotations

import os

BYTES_PER_KIB = 1024
BYTES_PER_MIB = BYTES_PER_KIB * BYTES_PER_KIB

DEFAULT_GITHUB_PUBLIC_HTML_MAX_DOWNLOAD_BYTES = 1 * BYTES_PER_MIB
DEFAULT_GITHUB_PUBLIC_TREE_MAX_DOWNLOAD_BYTES = 8 * BYTES_PER_MIB
DEFAULT_GITHUB_PUBLIC_ARCHIVE_MAX_DOWNLOAD_BYTES = 32 * BYTES_PER_MIB
DEFAULT_GITHUB_PUBLIC_ARCHIVE_MAX_ENTRY_COUNT = 10_000
DEFAULT_GITHUB_PUBLIC_ARCHIVE_MAX_SINGLE_FILE_BYTES = 8 * BYTES_PER_MIB
DEFAULT_GITHUB_PUBLIC_ARCHIVE_MAX_TOTAL_UNCOMPRESSED_BYTES = 64 * BYTES_PER_MIB
DEFAULT_GITHUB_PUBLIC_FETCH_CHUNK_BYTES = 64 * BYTES_PER_KIB


def _read_int_env(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        value = int(raw)
    except ValueError:
        return default
    return value if value > 0 else default


GITHUB_PUBLIC_HTML_MAX_DOWNLOAD_BYTES = _read_int_env(
    "URDF_GITHUB_PUBLIC_HTML_MAX_DOWNLOAD_BYTES",
    DEFAULT_GITHUB_PUBLIC_HTML_MAX_DOWNLOAD_BYTES,
)
GITHUB_PUBLIC_TREE_MAX_DOWNLOAD_BYTES = _read_int_env(
    "URDF_GITHUB_PUBLIC_TREE_MAX_DOWNLOAD_BYTES",
    DEFAULT_GITHUB_PUBLIC_TREE_MAX_DOWNLOAD_BYTES,
)
GITHUB_PUBLIC_ARCHIVE_MAX_DOWNLOAD_BYTES = _read_int_env(
    "URDF_GITHUB_PUBLIC_ARCHIVE_MAX_DOWNLOAD_BYTES",
    DEFAULT_GITHUB_PUBLIC_ARCHIVE_MAX_DOWNLOAD_BYTES,
)
GITHUB_PUBLIC_ARCHIVE_MAX_ENTRY_COUNT = _read_int_env(
    "URDF_GITHUB_PUBLIC_ARCHIVE_MAX_ENTRY_COUNT",
    DEFAULT_GITHUB_PUBLIC_ARCHIVE_MAX_ENTRY_COUNT,
)
GITHUB_PUBLIC_ARCHIVE_MAX_SINGLE_FILE_BYTES = _read_int_env(
    "URDF_GITHUB_PUBLIC_ARCHIVE_MAX_SINGLE_FILE_BYTES",
    DEFAULT_GITHUB_PUBLIC_ARCHIVE_MAX_SINGLE_FILE_BYTES,
)
GITHUB_PUBLIC_ARCHIVE_MAX_TOTAL_UNCOMPRESSED_BYTES = _read_int_env(
    "URDF_GITHUB_PUBLIC_ARCHIVE_MAX_TOTAL_UNCOMPRESSED_BYTES",
    DEFAULT_GITHUB_PUBLIC_ARCHIVE_MAX_TOTAL_UNCOMPRESSED_BYTES,
)
GITHUB_PUBLIC_FETCH_CHUNK_BYTES = _read_int_env(
    "URDF_GITHUB_PUBLIC_FETCH_CHUNK_BYTES",
    DEFAULT_GITHUB_PUBLIC_FETCH_CHUNK_BYTES,
)
