from __future__ import annotations

from backend.core.paths import BASE_DIR


SIMULATION_PREP_MUJOCO_TEST_ENV = "URDF_STUDIO_RUN_MUJOCO_TESTS"
SIMULATION_PREP_MUJOCO_STAGE_URDF_FILENAME = "simulation_prep_staged.urdf"
SIMULATION_PREP_MUJOCO_STAGE_MJCF_FILENAME = "simulation_prep_mesh_validation.xml"
SIMULATION_PREP_MUJOCO_MODEL_NAME = "simulation_prep_mesh_validation"
SIMULATION_PREP_MUJOCO_STAGE_BODY_NAME = "simulation_prep_mesh_validation_body"

SIMULATION_PREP_MUJOCO_SMOKE_STEP_COUNT = 32
SIMULATION_PREP_MUJOCO_VECTOR_COMPONENT_COUNT = 3
SIMULATION_PREP_MUJOCO_QUATERNION_COMPONENT_COUNT = 4

SIMULATION_PREP_MUJOCO_POSE_TOLERANCE = 1e-6
SIMULATION_PREP_MUJOCO_SCALE_TOLERANCE = 1e-9
SIMULATION_PREP_MUJOCO_QUATERNION_NORM_TOLERANCE = 1e-6

SIMULATION_PREP_MUJOCO_DEFAULT_POSITION = (0.0, 0.0, 0.0)
SIMULATION_PREP_MUJOCO_DEFAULT_RPY = (0.0, 0.0, 0.0)
SIMULATION_PREP_MUJOCO_DEFAULT_SCALE = (1.0, 1.0, 1.0)

SIMULATION_PREP_MUJOCO_DEMO_URDF_PATH = BASE_DIR / "web" / "public" / "demo" / "lekiwi.urdf"
