from __future__ import annotations

from pathlib import Path

TELEOP_REPLAY_SCHEMA_VERSION = "urdf-studio.teleop-replay.v1"
TELEOP_REPLAY_OPERATOR_ID = "urdf-studio-replay-engine"
TELEOP_REPLAY_DEFAULT_JOINT_TOLERANCE_RAD = 1e-6
TELEOP_REPLAY_OUTPUT_ROOT = Path("/tmp/urdf-studio-teleop-replays")
TELEOP_REPLAY_DEFAULT_FPS = 10
TELEOP_REPLAY_FPS_IS_NOMINAL = True
TELEOP_REPLAY_TASK_INDEX = 0
TELEOP_REPLAY_EPISODE_INDEX = 0
TELEOP_REPLAY_DATA_CHUNK_INDEX = 0
TELEOP_REPLAY_FILE_INDEX = 0
TELEOP_REPLAY_FIRST_DATASET_INDEX = 0
TELEOP_REPLAY_SINGLE_EPISODE_COUNT = 1
TELEOP_REPLAY_SINGLE_TASK_COUNT = 1
TELEOP_REPLAY_NO_REPLAYED_SAMPLE_COUNT = 0
TELEOP_REPLAY_SCALAR_FEATURE_SHAPE = (1,)
TELEOP_REPLAY_MILLISECONDS_PER_SECOND = 1_000.0
TELEOP_REPLAY_JSON_INDENT_SPACES = 2
TELEOP_REPLAY_ZERO_MILLISECONDS = 0.0
TELEOP_REPLAY_ZERO_TIMESTAMP_SECONDS = 0.0
TELEOP_REPLAY_ZERO_JOINT_RAD = 0.0
TELEOP_REPLAY_ZERO_JOINT_ERROR_RAD = 0.0
TELEOP_REPLAY_ZERO_FEATURE_VALUE = 0.0
TELEOP_REPLAY_EMPTY_STATS_COUNT = 0
TELEOP_REPLAY_MIN_JOINT_TOLERANCE_RAD = 0.0
TELEOP_REPLAY_TIMING_MODE_LOGICAL = "logical"
TELEOP_REPLAY_TIMING_MODE_WALL_CLOCK = "wall_clock"
TELEOP_REPLAY_TIMESTAMP_SEMANTICS_COMMAND_SOURCE = "command_source_time"
TELEOP_REPLAY_FPS_SEMANTICS_NOMINAL_IRREGULAR = "nominal_irregular_rows"
TELEOP_REPLAY_PARQUET_CHUNK_NAME = "chunk-000"
TELEOP_REPLAY_PARQUET_FILE_NAME = "file-000.parquet"
TELEOP_REPLAY_META_FILENAME = "urdf_studio_replay.json"
TELEOP_REPLAY_INFO_FILENAME = "info.json"
TELEOP_REPLAY_STATS_FILENAME = "stats.json"
TELEOP_REPLAY_TASKS_FILENAME = "tasks.parquet"
TELEOP_REPLAY_FEATURE_DTYPE_FLOAT32 = "float32"
TELEOP_REPLAY_FEATURE_DTYPE_INT64 = "int64"
TELEOP_REPLAY_CODEBASE_VERSION = "urdf-studio-teleop-replay"
TELEOP_REPLAY_DATASET_FORMAT_VERSION = "lerobot_dataset_v3"
TELEOP_REPLAY_CHUNKS_SIZE = 1_000
TELEOP_REPLAY_EXPORT_MODE_GATEWAY_REPLAY = "gateway_replay"
TELEOP_REPLAY_EXPORT_MODE_STUDIO_KINEMATIC = "studio_kinematic"
TELEOP_REPLAY_COMMAND_KIND_JOINT_JOG = "joint_jog"
TELEOP_REPLAY_COMMAND_KIND_STOP = "stop"
TELEOP_REPLAY_COMMAND_KIND_ESTOP = "estop"
TELEOP_REPLAY_COMMAND_KIND_JOINT_TARGETS = "joint_targets"
TELEOP_REPLAY_COMMAND_KIND_TWIST = "twist"
TELEOP_REPLAY_GATEWAY_REPLAY_COMMAND_KINDS = frozenset(
    {
        TELEOP_REPLAY_COMMAND_KIND_JOINT_JOG,
        TELEOP_REPLAY_COMMAND_KIND_STOP,
        TELEOP_REPLAY_COMMAND_KIND_ESTOP,
    }
)
TELEOP_REPLAY_ACTION_SEMANTICS_GATEWAY_DELTA = "gateway_joint_delta"
TELEOP_REPLAY_ACTION_SEMANTICS_KINEMATIC_ABSOLUTE = "absolute_joint_targets"
TELEOP_REPLAY_OBSERVATION_SEMANTICS_GATEWAY_STATE = "gateway_joint_state"
TELEOP_REPLAY_OBSERVATION_SEMANTICS_KINEMATIC_PROXY = "studio_joint_state_proxy"
TELEOP_REPLAY_CONTEXT_TELEOPERATION_MODE_STUDIO_KINEMATIC = "studio_kinematic"
TELEOP_REPLAY_CONTEXT_INPUT_SOURCE_IK_DRAG = "ik_drag"
TELEOP_REPLAY_CONTEXT_PHYSICS_SOURCE_NONE = "none"
TELEOP_REPLAY_CONTEXT_PHYSICS_SOURCE_GATEWAY_PROXY = "gateway_proxy"
TELEOP_REPLAY_CONTEXT_REPLAY_GUARANTEE_KINEMATIC = "kinematic"
TELEOP_REPLAY_MJLAB_EXPORT_REJECTION_PREFIX = "MJLab validation rejected export"
TELEOP_REPLAY_MJLAB_EXPORT_REJECTION_ISSUE_PREVIEW_COUNT = 3
TELEOP_REPLAY_MJLAB_EXPORT_SELF_COLLISION_UNCHECKED = (
    "MJLab export requires completed self-collision validation with the active "
    "robot model."
)
TELEOP_REPLAY_MJLAB_EXPORT_GATE_REQUIRED = (
    "LeRobot export requires an MJLab export gate result."
)
TELEOP_REPLAY_MJLAB_EXPORT_GATE_RECORDING_MISMATCH = (
    "MJLab export gate recording ID does not match the recording."
)


def format_teleop_replay_run_id(recording_id: str) -> str:
    normalized = "".join(
        character if character.isalnum() or character in {"-", "_"} else "-"
        for character in recording_id.strip()
    ).strip("-")
    return normalized or "teleop-recording"
