from __future__ import annotations

TELEOP_MJLAB_SCHEMA_VERSION = "urdf-studio.teleop-mjlab-validation.v1"
TELEOP_MJLAB_BUNDLE_KIND = "urdf_studio_mjlab_validation_bundle"
TELEOP_MJLAB_RUNTIME_NAME = "mjlab"
TELEOP_MJLAB_RUNTIME_STATUS_AVAILABLE = "available"
TELEOP_MJLAB_RUNTIME_STATUS_UNAVAILABLE = "unavailable"
TELEOP_MJLAB_RUNTIME_DEPENDENCY_MJLAB = "mjlab"
TELEOP_MJLAB_RUNTIME_DEPENDENCY_MUJOCO = "mujoco"
TELEOP_MJLAB_TRAJECTORY_SOURCE_RECORDED_JOINT_STATE = "recorded_joint_state"
TELEOP_MJLAB_TRAJECTORY_SOURCE_STUDIO_JOINT_TARGETS = "studio_joint_targets"
TELEOP_MJLAB_TIMESTAMP_SEMANTICS_COMMAND_SOURCE = "command_source_time_ms"
TELEOP_MJLAB_ISSUE_SEVERITY_ERROR = "error"
TELEOP_MJLAB_ISSUE_SEVERITY_WARNING = "warning"
TELEOP_MJLAB_ISSUE_CODE_EMPTY_RECORDING = "empty_recording"
TELEOP_MJLAB_ISSUE_CODE_SHORT_TRAJECTORY = "short_trajectory"
TELEOP_MJLAB_ISSUE_CODE_MISSING_JOINT_STATE = "missing_joint_state"
TELEOP_MJLAB_ISSUE_CODE_NON_MONOTONIC_TIMESTAMP = "non_monotonic_timestamp"
TELEOP_MJLAB_ISSUE_CODE_TIMESTAMP_GAP = "timestamp_gap"
TELEOP_MJLAB_ISSUE_CODE_JOINT_VELOCITY_LIMIT = "joint_velocity_limit"
TELEOP_MJLAB_ISSUE_CODE_JOINT_ACCELERATION_LIMIT = "joint_acceleration_limit"
TELEOP_MJLAB_ISSUE_CODE_SELF_COLLISION = "self_collision"
TELEOP_MJLAB_ISSUE_CODE_SELF_COLLISION_MODEL_MISSING = "self_collision_model_missing"
TELEOP_MJLAB_ISSUE_CODE_SELF_COLLISION_MODEL_INVALID = "self_collision_model_invalid"
TELEOP_MJLAB_ISSUE_CODE_SELF_COLLISION_RUNTIME_UNAVAILABLE = (
    "self_collision_runtime_unavailable"
)
TELEOP_MJLAB_DEFAULT_MAX_JOINT_VELOCITY_RAD_PER_SEC = 12.0
TELEOP_MJLAB_DEFAULT_MAX_JOINT_ACCELERATION_RAD_PER_SEC2 = 120.0
TELEOP_MJLAB_DEFAULT_MAX_TIMESTAMP_GAP_MS = 250.0
TELEOP_MJLAB_DEFAULT_REQUIRE_SELF_COLLISION_CHECK = True
TELEOP_MJLAB_DEFAULT_MAX_SELF_COLLISION_DISTANCE_M = 0.0
TELEOP_MJLAB_MIN_TRAJECTORY_SAMPLE_COUNT = 2
TELEOP_MJLAB_MAX_SELF_COLLISION_ISSUES = 100
TELEOP_MJLAB_STAGED_MESH_DIRNAME = "meshes"
TELEOP_MJLAB_STAGED_MESH_FILENAME_PREFIX = "mesh"
TELEOP_MJLAB_ZERO_TIMESTAMP_MS = 0.0
TELEOP_MJLAB_ZERO_DURATION_MS = 0.0
TELEOP_MJLAB_ZERO_METRIC = 0.0
TELEOP_MJLAB_WORLD_BODY_ID = 0
TELEOP_MJLAB_MILLISECONDS_PER_SECOND = 1_000.0
TELEOP_MJLAB_RUNTIME_DEPENDENCIES = (
    TELEOP_MJLAB_RUNTIME_DEPENDENCY_MJLAB,
    TELEOP_MJLAB_RUNTIME_DEPENDENCY_MUJOCO,
)
