from __future__ import annotations

WORLD_SCENE_PACKAGE_SCHEMA_VERSION_V1 = "1.0.0"
WORLD_SCENE_PACKAGE_SCHEMA_VERSION_V1_1 = "1.1.0"
WORLD_SCENE_PACKAGE_SCHEMA_VERSIONS = (
    WORLD_SCENE_PACKAGE_SCHEMA_VERSION_V1,
    WORLD_SCENE_PACKAGE_SCHEMA_VERSION_V1_1,
)

MIN_SCENARIO_TIME_MS = 0
MIN_SCENARIO_DURATION_MS = 0
MAX_SCENARIO_DURATION_MS = 600_000

MAX_RUNTIME_TARGETS = 16
MAX_INTERFACE_MODALITIES = 32
MAX_ARTIFACT_REFS = 128
MAX_CAMERAS_PER_WORLD = 64
MAX_OBJECTS_PER_WORLD = 256
MAX_JOINTS_PER_WORLD = 512
MAX_WORLD_SNAPSHOT_URDF_CHARS = 500_000
MAX_WORLD_SCENE_PACKAGE_MANIFEST_BYTES = 1_000_000
SHA256_HEX_LENGTH = 64
REGISTRY_FILE_VERSION = 1

DEFAULT_WORLD_REGISTRY_FILENAME = ".urdf-studio-world-registry.json"

WORLD_SCENE_PACKAGE_TRUST_METADATA_ONLY = "metadata_only"
WORLD_SCENE_PACKAGE_TRUST_SIGNED_METADATA = "signed_metadata"
WORLD_SCENE_PACKAGE_TRUST_METADATA_COMPLETE = "metadata_complete"
