from __future__ import annotations

DEFAULT_WORLD_ROLLOUT_WORKSPACE_ROOT = "/tmp/urdf-studio-rollouts"
DEFAULT_WORLD_ROLLOUT_TIMEOUT_SECONDS = 600
DEFAULT_WORLD_ROLLOUT_MAX_OUTPUT_CHARS = 200_000
DEFAULT_WORLD_ROLLOUT_MAX_WORKERS = 2
DEFAULT_WORLD_ROLLOUT_MAX_QUEUED_JOBS = 16

WORLD_ROLLOUT_CHECKER_PROFILE_SCHEMA_VERSION = "world_rollout_checker_profile.v1"
WORLD_ROLLOUT_CAMPAIGN_SCHEMA_VERSION = "world_rollout_campaign.v1"
WORLD_ROLLOUT_DEFAULT_RUNNER_KIND = "local-cli"
WORLD_ROLLOUT_JOB_ID_PREFIX = "wroll"

WORLD_ROLLOUT_INPUT_CAMPAIGN_FILENAME = "campaign.json"
WORLD_ROLLOUT_INPUT_WORLD_PACKAGE_FILENAME = "world_package.json"
WORLD_ROLLOUT_INPUT_CHECKER_PROFILE_FILENAME = "checker_profile.json"
WORLD_ROLLOUT_OUTPUT_CAMPAIGN_FILENAME = "world_rollout_campaign.v1.json"
WORLD_ROLLOUT_OUTPUT_DIRNAME = "out"
WORLD_ROLLOUT_WORLD_PACKAGE_ARTIFACT_KIND = "world_package_manifest"
WORLD_ROLLOUT_CHECKER_PROFILE_ARTIFACT_KIND = "checker_profile"
WORLD_ROLLOUT_TRACE_ARTIFACT_KIND = "trace_ndjson"
WORLD_ROLLOUT_DECISIONS_ARTIFACT_KIND = "decisions_ndjson"

WORLD_ROLLOUT_MAX_ARTIFACT_REFS = 128
WORLD_ROLLOUT_MAX_MODULE_SPECS = 64
WORLD_ROLLOUT_MAX_TRACE_RECORDS = 100_000
WORLD_ROLLOUT_MAX_DECISION_RECORDS = 100_000
WORLD_ROLLOUT_MAX_JSON_BYTES = 25_000_000
WORLD_ROLLOUT_MAX_NDJSON_BYTES = 25_000_000
WORLD_ROLLOUT_MAX_JOB_STDIO_CHARS = 20_000
WORLD_ROLLOUT_MAX_JOBS = 128
WORLD_ROLLOUT_DECISION_ALLOW = "allow"
WORLD_ROLLOUT_DECISION_WARN = "warn"
WORLD_ROLLOUT_DECISION_REJECT = "reject"
WORLD_ROLLOUT_DECISION_STOP = "stop"
WORLD_ROLLOUT_DECISION_ESCALATE = "escalate"
WORLD_ROLLOUT_DECISIONS = frozenset(
    (
        WORLD_ROLLOUT_DECISION_ALLOW,
        WORLD_ROLLOUT_DECISION_WARN,
        WORLD_ROLLOUT_DECISION_REJECT,
        WORLD_ROLLOUT_DECISION_STOP,
        WORLD_ROLLOUT_DECISION_ESCALATE,
    )
)
