export const PACKAGE_SURFACE_CHECK = {
  npmCommand: "npm",
  npmPackDryRunArgs: ["pack", "--dry-run", "--json"],
  npmignorePath: ".npmignore",
  maxEntryCount: 1500,
  maxPackedBytes: 60 * 1024 * 1024,
  maxUnpackedBytes: 120 * 1024 * 1024,
  blockedPathPrefixes: [
    ".github/",
    ".gitmodules",
    "third_party/",
    "backend/tests/",
    "docs/architecture/",
    "reports/",
    ".cache/",
    ".uv-cache/",
    ".venv/",
    ".venv-lerobot/",
    ".i-love-urdf/",
    "node_modules/",
    "web/node_modules/",
    "dist/",
    "web/dist/",
    "amd-hackathon/",
    "pyroki/",
    "vggt/",
  ],
  blockedPathPatterns: [
    /^\.env($|\.)/,
    /^\.npmrc$/,
    /^\.urdf-studio-(config|version-check)\.json$/,
    /(^|\/)__pycache__\//,
    /(^|\/)\.DS_Store$/,
    /\.py[co]$/,
    /\.test\.[cm]?[jt]sx?$/,
    /\.tsbuildinfo$/,
  ],
};
