import type { Camera } from "@/shared/types/camera";
import { normalizeCameraIntrinsics } from "@/shared/lib/cameraIntrinsics";
import { toFiniteNumberOrFallback } from "@/shared/lib/numeric";
import {
  CAMERA_AUTO_UPDATE_EPSILON,
  DEFAULT_CAMERA_POSE,
  CAMERA_AUTO_GENERATION_HELPER_PARAMS,
} from "./cameraAutoGenerationParams";

export type CameraPose = {
  xyz: [number, number, number];
  rpy: [number, number, number];
};

const AUTO_CAMERA_NAME_PREFIX = CAMERA_AUTO_GENERATION_HELPER_PARAMS.autoCameraNamePrefix;

export const decodeUriComponentSafe = (value: string) => {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
};

export const toAutoCameraName = (linkName: string) =>
  `${AUTO_CAMERA_NAME_PREFIX}${linkName}`;

export const isAutoGeneratedCameraName = (name: string) =>
  name.startsWith(AUTO_CAMERA_NAME_PREFIX);

export const toSafeCameraPose = (
  pose?: { xyz?: [number, number, number]; rpy?: [number, number, number] } | null
): CameraPose => {
  const xyz = pose?.xyz ?? DEFAULT_CAMERA_POSE.xyz;
  const rpy = pose?.rpy ?? DEFAULT_CAMERA_POSE.rpy;
  return {
    xyz: [
      toFiniteNumberOrFallback(xyz[0], DEFAULT_CAMERA_POSE.xyz[0]),
      toFiniteNumberOrFallback(xyz[1], DEFAULT_CAMERA_POSE.xyz[1]),
      toFiniteNumberOrFallback(xyz[2], DEFAULT_CAMERA_POSE.xyz[2]),
    ],
    rpy: [
      toFiniteNumberOrFallback(rpy[0], DEFAULT_CAMERA_POSE.rpy[0]),
      toFiniteNumberOrFallback(rpy[1], DEFAULT_CAMERA_POSE.rpy[1]),
      toFiniteNumberOrFallback(rpy[2], DEFAULT_CAMERA_POSE.rpy[2]),
    ],
  };
};

const numbersClose = (
  left: number,
  right: number,
  epsilon = CAMERA_AUTO_UPDATE_EPSILON
) => Math.abs(left - right) <= epsilon;

const triplesClose = (
  left: [number, number, number],
  right: [number, number, number],
  epsilon = CAMERA_AUTO_UPDATE_EPSILON
) =>
  numbersClose(left[0], right[0], epsilon) &&
  numbersClose(left[1], right[1], epsilon) &&
  numbersClose(left[2], right[2], epsilon);

export const cameraPoseClose = (left: CameraPose, right: CameraPose) =>
  triplesClose(left.xyz, right.xyz) && triplesClose(left.rpy, right.rpy);

export const cameraIntrinsicsClose = (
  left: ReturnType<typeof normalizeCameraIntrinsics>,
  right: ReturnType<typeof normalizeCameraIntrinsics>
) =>
  numbersClose(left.width, right.width, 0) &&
  numbersClose(left.height, right.height, 0) &&
  numbersClose(left.fov_deg, right.fov_deg) &&
  numbersClose(left.fx, right.fx) &&
  numbersClose(left.fy, right.fy) &&
  numbersClose(left.cx, right.cx) &&
  numbersClose(left.cy, right.cy);

export const buildCameraMapByName = (cameras: Camera[]) =>
  new Map(cameras.map((camera) => [camera.name, camera] as const));
