import { describe, expect, it } from "vitest";
import { normalizeCameraIntrinsics } from "@/shared/lib/cameraIntrinsics";
import {
  cameraIntrinsicsClose,
  cameraPoseClose,
  decodeUriComponentSafe,
  isAutoGeneratedCameraName,
  toAutoCameraName,
  toSafeCameraPose,
} from "./cameraAutoGenerationHelpers";

const AUTO_CAMERA_LINK_NAME = "camera_link";
const AUTO_CAMERA_FULL_NAME = "Auto Camera: camera_link";
const ENCODED_CAMERA_NAME = "camera%20mount";
const DECODED_CAMERA_NAME = "camera mount";
const INVALID_ENCODED_CAMERA_NAME = "%E0%A4%A";
const POSE_XYZ_SAFE_X = 1;
const POSE_XYZ_SAFE_Z = 3;
const POSE_RPY_SAFE_Y = 0.2;
const POSE_RPY_SAFE_Z = -0.1;
const CAMERA_WIDTH = 640;
const CAMERA_HEIGHT = 480;
const CAMERA_FOV_DEG = 78;
const POSE_A_X = 1;
const POSE_A_Y = 2;
const POSE_A_Z = 3;
const POSE_A_ROLL = 0.1;
const POSE_A_PITCH = 0.2;
const POSE_A_YAW = 0.3;

describe("cameraAutoGenerationHelpers", () => {
  it("generates and detects auto camera names", () => {
    const name = toAutoCameraName(AUTO_CAMERA_LINK_NAME);
    expect(name).toBe(AUTO_CAMERA_FULL_NAME);
    expect(isAutoGeneratedCameraName(name)).toBe(true);
    expect(isAutoGeneratedCameraName("manual camera")).toBe(false);
  });

  it("decodes URI components safely", () => {
    expect(decodeUriComponentSafe(ENCODED_CAMERA_NAME)).toBe(DECODED_CAMERA_NAME);
    expect(decodeUriComponentSafe(INVALID_ENCODED_CAMERA_NAME)).toBe(
      INVALID_ENCODED_CAMERA_NAME
    );
  });

  it("normalizes camera poses with numeric fallbacks", () => {
    const pose = toSafeCameraPose({
      xyz: [POSE_XYZ_SAFE_X, Number.NaN, POSE_XYZ_SAFE_Z],
      rpy: [Infinity, POSE_RPY_SAFE_Y, POSE_RPY_SAFE_Z],
    });
    expect(pose.xyz).toEqual([POSE_XYZ_SAFE_X, 0, POSE_XYZ_SAFE_Z]);
    expect(pose.rpy).toEqual([0, POSE_RPY_SAFE_Y, POSE_RPY_SAFE_Z]);
  });

  it("compares pose and intrinsics snapshots", () => {
    expect(
      cameraPoseClose(
        {
          xyz: [POSE_A_X, POSE_A_Y, POSE_A_Z],
          rpy: [POSE_A_ROLL, POSE_A_PITCH, POSE_A_YAW],
        },
        {
          xyz: [POSE_A_X, POSE_A_Y, POSE_A_Z],
          rpy: [POSE_A_ROLL, POSE_A_PITCH, POSE_A_YAW],
        }
      )
    ).toBe(true);

    const intrinsicsA = normalizeCameraIntrinsics({
      width: CAMERA_WIDTH,
      height: CAMERA_HEIGHT,
      fov_deg: CAMERA_FOV_DEG,
    });
    const intrinsicsB = normalizeCameraIntrinsics({
      width: CAMERA_WIDTH,
      height: CAMERA_HEIGHT,
      fov_deg: CAMERA_FOV_DEG,
    });
    expect(cameraIntrinsicsClose(intrinsicsA, intrinsicsB)).toBe(true);
  });
});
