export const CAMERA_LINK_PREFIX_PATTERN = /^camera/i;
export const DEFAULT_CAMERA_WIDTH = 640;
export const DEFAULT_CAMERA_HEIGHT = 480;
export const DEFAULT_CAMERA_FOV_DEG = 78;
export const CAMERA_AUTO_CENTROID_MIN_TRIANGLE_AREA = 1e-14;
export const CAMERA_AUTO_CENTROID_MIN_TOTAL_WEIGHT = 1e-12;
export const CAMERA_AUTO_CENTROID_MIN_TOTAL_SIGNED_VOLUME = 1e-14;
const CAMERA_AUTO_RECONCILE_INTERVAL_MS = 120;
const CAMERA_AUTO_RECONCILE_MAX_DURATION_MS = 12_000;
const CAMERA_AUTO_RECONCILE_MAX_ATTEMPTS = Math.ceil(
  CAMERA_AUTO_RECONCILE_MAX_DURATION_MS / CAMERA_AUTO_RECONCILE_INTERVAL_MS
);
export const CAMERA_AUTO_UPDATE_EPSILON = 1e-6;
export const CAMERA_AUTO_OUTWARD_MIN_VECTOR_LENGTH = 1e-8;
export const CAMERA_AUTO_OUTWARD_UP_PARALLEL_DOT = 0.95;
const CAMERA_AUTO_DIRECTION_CUE_MIN_LINK_SPAN = 1e-5;
export const CAMERA_AUTO_DIRECTION_CUE_MIN_VECTOR_LENGTH = 1e-8;
const CAMERA_AUTO_DIRECTION_CUE_FRONT_CONFIDENCE_MIN = 0.14;
const CAMERA_AUTO_DIRECTION_CUE_COVARIANCE_MIN_EIGENVALUE = 1e-14;
const CAMERA_AUTO_DIRECTION_CUE_POWER_ITERATION_STEPS = 28;
const CAMERA_AUTO_DIRECTION_CUE_AXIS_ORTHOGONAL_DOT_MAX = 0.98;
const CAMERA_AUTO_DIRECTION_CUE_EXTENT_EPSILON = 1e-12;
const CAMERA_AUTO_DIRECTION_CUE_FRONT_DISTANCE_RATIO = 0.92;
const CAMERA_AUTO_DIRECTION_CUE_FRONT_MIN_SAMPLE_COUNT = 8;
const CAMERA_AUTO_DIRECTION_CUE_EXTENT_WEIGHT = 0.75;
const CAMERA_AUTO_DIRECTION_CUE_SUPPORT_WEIGHT = 0.25;
const CAMERA_AUTO_DIRECTION_CUE_UP_ALIGNMENT_WEIGHT = 0.85;
const CAMERA_AUTO_DIRECTION_CUE_UP_SPAN_WEIGHT = 0.15;
export const CAMERA_AUTO_FRAME_CUE_MIN_POINT_COUNT = 16;
export const CAMERA_AUTO_FRAME_CUE_MIN_PLANAR_VARIANCE = 1e-10;
export const CAMERA_AUTO_FRAME_CUE_CONFIDENCE_MIN = 0.15;
export const CAMERA_AUTO_FRAME_CUE_EPSILON = 1e-12;
export const CAMERA_AUTO_MESH_FRAME_FORWARD_WEIGHT = 0.7;
export const CAMERA_AUTO_MESH_FRAME_UP_WEIGHT = 0.3;
export const CAMERA_AUTO_MESH_FRAME_MIN_ALIGNMENT = 0.25;
const CAMERA_AUTO_FLOOR_UP_FALLBACK_DOT_MIN = 0.995;
export const CAMERA_AUTO_MOUNT_ALGO_VERSION = 6;
export const CAMERA_ORIENTATION_DOT_EPSILON_STRICT = 0.999;
const CAMERA_ORIENTATION_DOT_EPSILON_WARN = 0.995;
const LEGACY_DEMO_CAMERA_NAMES = ["Gripper Top", "Base Front"] as const;
export const LEGACY_DEMO_CAMERA_NAME_SET = new Set<string>(LEGACY_DEMO_CAMERA_NAMES);
export const DEFAULT_CAMERA_POSE = {
  xyz: [0, 0, 0] as [number, number, number],
  rpy: [0, 0, 0] as [number, number, number],
};


export const CAMERA_AUTO_GENERATION_HELPER_PARAMS = {
  autoCameraNamePrefix: "Auto Camera: ",
} as const;
