import { useCallback, useRef, useState } from "react";
import * as THREE from "three";
import type { URDFRobot } from "urdf-loader";
import type { UrdfAnalysis } from "@/shared/lib/urdfCore";
import type { Camera } from "@/shared/types/camera";
import { normalizeCameraIntrinsics } from "@/shared/lib/cameraIntrinsics";
import {
  remapCameraPoseToParentJointFrame,
  resolveCameraParentJointNameFromLink,
} from "./cameraWorldPose";
import { partitionLegacyFallbackCameras } from "./cameraAutoCleanup";
import { resolveAutoCameraLinks } from "./cameraAutoTargets";
import {
  CAMERA_AUTO_MOUNT_ALGO_VERSION,
  DEFAULT_CAMERA_FOV_DEG,
  DEFAULT_CAMERA_HEIGHT,
  DEFAULT_CAMERA_WIDTH,
} from "./cameraAutoGenerationParams";
import type { CameraPose } from "./cameraAutoGenerationHelpers";
import {
  buildCameraMapByName,
  cameraIntrinsicsClose,
  cameraPoseClose,
  decodeUriComponentSafe,
  isAutoGeneratedCameraName,
  toAutoCameraName,
  toSafeCameraPose,
} from "./cameraAutoGenerationHelpers";
import {
  resolveCameraPoseAtLocalPointFacingOutward,
} from "./cameraAutoPlacement";
import {
  computeOwnedLinkLocalVisualMeshAlignedFrameCue,
  computeOwnedLinkLocalVisualMeshAlignedForwardCue,
  computeOwnedLinkLocalVisualMeshAlignedUpCue,
  computeOwnedLinkLocalVisualBounds,
  computeOwnedLinkLocalVisualCentroid,
  computeOwnedLinkLocalVisualDirectionCue,
  computeOwnedLinkLocalVisualFrameCue,
  computeOwnedLinkLocalVisualPrincipalAxis,
} from "./cameraAutoBounds";
import { resolvePreferredOrientationFromCues } from "./cameraAutoOrientationSelection";
import { computeOwnedLinkDominantBasisFrameCue } from "./cameraEnvelopeFit";

type CameraAutoMount = {
  linkName: string;
  parentJoint: string;
  name: string;
  pose: CameraPose;
  hasGeometry: boolean;
};

type CameraMountResolution = {
  mounts: CameraAutoMount[];
};

type LinkCenterResolution = {
  pose: CameraPose;
  hasGeometry: boolean;
};

type UseCameraAutoGenerationOptions = {
  robot: URDFRobot | null;
  urdfAnalysis: UrdfAnalysis | null | undefined;
  availableLinks: string[];
  thumbnailMode: boolean;
  loadSignature: string;
  addCamera: (camera: Omit<Camera, "id">) => void;
  updateCamera: (id: string, updates: Partial<Omit<Camera, "id">>) => void;
  removeCamera: (id: string) => void;
};

export type AutoCameraBootstrapState = "blocked" | "pending-geometry" | "settled";

export const useCameraAutoGeneration = ({
  robot,
  urdfAnalysis,
  availableLinks,
  thumbnailMode,
  loadSignature,
  addCamera,
  updateCamera,
  removeCamera,
}: UseCameraAutoGenerationOptions) => {
  const hasPendingAutoCameraGeometryRef = useRef(false);
  const autoCameraLoadSignatureRef = useRef("");
  const frozenAutoMountByNameRef = useRef<Map<string, CameraAutoMount>>(new Map());
  const [autoCameraBootstrapState, setAutoCameraBootstrapState] =
    useState<AutoCameraBootstrapState>("blocked");
  const effectiveLoadSignature = `${loadSignature}::algo-${CAMERA_AUTO_MOUNT_ALGO_VERSION}`;

  const setBootstrapState = useCallback((nextState: AutoCameraBootstrapState) => {
    setAutoCameraBootstrapState((currentState) =>
      currentState === nextState ? currentState : nextState
    );
  }, []);

  const resolveCameraParentJointFromLink = useCallback(
    (linkName: string | null | undefined) => {
      const normalized = typeof linkName === "string" ? linkName.trim() : "";
      if (!normalized) return null;

      const decoded = decodeUriComponentSafe(normalized);
      const hierarchyMatch =
        urdfAnalysis?.jointHierarchy?.orderedJoints?.find(
          (joint) => joint.childLink === normalized || joint.childLink === decoded
        ) ?? null;
      if (hierarchyMatch?.jointName) return hierarchyMatch.jointName;

      return resolveCameraParentJointNameFromLink(robot, normalized);
    },
    [robot, urdfAnalysis?.jointHierarchy?.orderedJoints]
  );

  const resolveRobotLinkObject = useCallback(
    (linkName: string) => {
      if (!robot) return null;
      const decoded = decodeUriComponentSafe(linkName);
      return (
        robot.links?.[linkName] ??
        robot.links?.[decoded] ??
        robot.getObjectByName?.(linkName) ??
        (decoded !== linkName ? robot.getObjectByName?.(decoded) : null) ??
        null
      );
    },
    [robot]
  );

  const resolveLinkCenterPose = useCallback(
    (linkName: string): LinkCenterResolution => {
      const linkObject = resolveRobotLinkObject(linkName);
      if (!linkObject) {
        return { pose: toSafeCameraPose(), hasGeometry: false };
      }

      try {
        const resolvePoseAtLocalPoint = (localPoint: THREE.Vector3) => {
          const meshDirectionCue = computeOwnedLinkLocalVisualDirectionCue(linkObject, localPoint);
          const meshPrincipalAxis = meshDirectionCue
            ? null
            : computeOwnedLinkLocalVisualPrincipalAxis(linkObject, localPoint);
          const directionForward = meshDirectionCue ?? meshPrincipalAxis;
          const dominantBasisFrameCue = directionForward
            ? computeOwnedLinkDominantBasisFrameCue(linkObject, directionForward)
            : null;
          const meshFrameCueFromSurface = directionForward
            ? computeOwnedLinkLocalVisualFrameCue(linkObject, localPoint, directionForward)
            : null;
          const meshFrameCueFromAxis =
            directionForward &&
            !meshFrameCueFromSurface &&
            !dominantBasisFrameCue
              ? computeOwnedLinkLocalVisualMeshAlignedFrameCue(
                  linkObject,
                  directionForward
                )
              : null;
          const meshFrameCue =
            dominantBasisFrameCue ?? meshFrameCueFromSurface ?? meshFrameCueFromAxis;
          const desiredForward = meshFrameCue?.forward ?? directionForward;
          const meshAxisForwardCue =
            !meshFrameCue && desiredForward
              ? computeOwnedLinkLocalVisualMeshAlignedForwardCue(
                  linkObject,
                  desiredForward
                )
              : null;
          const preliminaryPreferredForward =
            meshFrameCue?.forward ?? meshAxisForwardCue ?? directionForward;
          const meshAxisUpCue =
            !meshFrameCue && preliminaryPreferredForward
              ? computeOwnedLinkLocalVisualMeshAlignedUpCue(
                  linkObject,
                  preliminaryPreferredForward
                )
              : null;
          const { preferredForward, preferredUp } = resolvePreferredOrientationFromCues({
            frameCue: meshFrameCue,
            directionForward,
            meshAxisForwardCue,
            meshAxisUpCue,
          });
          return resolveCameraPoseAtLocalPointFacingOutward(linkObject, localPoint, robot, {
            preferredForwardLocal: preferredForward,
            preferredUpLocal: preferredUp,
          });
        };

        const localVisualCentroid = computeOwnedLinkLocalVisualCentroid(linkObject);
        if (localVisualCentroid) {
          return {
            pose: toSafeCameraPose(resolvePoseAtLocalPoint(localVisualCentroid)),
            hasGeometry: true,
          };
        }

        const localVisualBounds = computeOwnedLinkLocalVisualBounds(linkObject);
        if (!localVisualBounds) {
          return { pose: toSafeCameraPose(), hasGeometry: false };
        }

        const boundsCenter = localVisualBounds.getCenter(new THREE.Vector3());
        return {
          pose: toSafeCameraPose(resolvePoseAtLocalPoint(boundsCenter)),
          hasGeometry: true,
        };
      } catch {
        return { pose: toSafeCameraPose(), hasGeometry: false };
      }
    },
    [resolveRobotLinkObject, robot]
  );

  const resolveCameraPrefixMounts = useCallback(() => {
    const candidateLinks = resolveAutoCameraLinks({
      availableLinks,
      joints: urdfAnalysis?.jointHierarchy?.orderedJoints ?? [],
      sensors: urdfAnalysis?.sensors ?? [],
    });
    const mounts: CameraAutoMount[] = [];
    candidateLinks.forEach((linkName) => {
      const parentJoint = resolveCameraParentJointFromLink(linkName);
      if (!parentJoint) return;
      const linkCenter = resolveLinkCenterPose(linkName);
      const jointFramePose = remapCameraPoseToParentJointFrame(
        robot,
        parentJoint,
        linkName,
        linkCenter.pose
      );
      mounts.push({
        linkName,
        parentJoint,
        name: toAutoCameraName(linkName),
        pose: jointFramePose,
        hasGeometry: linkCenter.hasGeometry,
      });
    });

    return { mounts } satisfies CameraMountResolution;
  }, [
    availableLinks,
    resolveCameraParentJointFromLink,
    resolveLinkCenterPose,
    robot,
    urdfAnalysis?.jointHierarchy?.orderedJoints,
    urdfAnalysis?.sensors,
  ]);

  const ensureDetectedCamerasForLoadedRobot = useCallback(
    (existingCameras: Camera[]) => {
      const loadSignatureChanged =
        autoCameraLoadSignatureRef.current !== effectiveLoadSignature;
      if (loadSignatureChanged) {
        autoCameraLoadSignatureRef.current = effectiveLoadSignature;
        frozenAutoMountByNameRef.current.clear();
      }

      const { retainedCameras, cameraIdsToRemove } = partitionLegacyFallbackCameras(existingCameras);
      const normalizedRetainedCameras: Camera[] = [];
      retainedCameras.forEach((camera) => {
        if (loadSignatureChanged && isAutoGeneratedCameraName(camera.name)) {
          cameraIdsToRemove.push(camera.id);
          return;
        }
        normalizedRetainedCameras.push(camera);
      });
      cameraIdsToRemove.forEach((cameraId) => removeCamera(cameraId));

      if (thumbnailMode || !robot || availableLinks.length === 0) {
        hasPendingAutoCameraGeometryRef.current = false;
        setBootstrapState(normalizedRetainedCameras.length > 0 ? "settled" : "blocked");
        return normalizedRetainedCameras.length > 0;
      }

      const { mounts } = resolveCameraPrefixMounts();
      const desiredNames = new Set(mounts.map((mount) => mount.name));
      frozenAutoMountByNameRef.current.forEach((_mount, mountName) => {
        if (!desiredNames.has(mountName)) {
          frozenAutoMountByNameRef.current.delete(mountName);
        }
      });

      const stableMounts: CameraAutoMount[] = [];
      let unresolvedMounts = 0;
      mounts.forEach((mount) => {
        const frozenMount = frozenAutoMountByNameRef.current.get(mount.name);
        if (frozenMount) {
          stableMounts.push(frozenMount);
          return;
        }
        if (!mount.hasGeometry) {
          unresolvedMounts += 1;
          return;
        }
        frozenAutoMountByNameRef.current.set(mount.name, mount);
        stableMounts.push(mount);
      });
      hasPendingAutoCameraGeometryRef.current = unresolvedMounts > 0;
      setBootstrapState(unresolvedMounts > 0 ? "pending-geometry" : "settled");

      const defaultIntrinsics = normalizeCameraIntrinsics({
        width: DEFAULT_CAMERA_WIDTH,
        height: DEFAULT_CAMERA_HEIGHT,
        fov_deg: DEFAULT_CAMERA_FOV_DEG,
      });
      const existingByName = buildCameraMapByName(normalizedRetainedCameras);

      stableMounts.forEach((mount) => {
        const existing = existingByName.get(mount.name);
        if (existing) {
          const needsUpdate =
            existing.parent_joint !== mount.parentJoint ||
            !cameraPoseClose(existing.pose, mount.pose) ||
            !cameraIntrinsicsClose(existing.intrinsics, defaultIntrinsics);
          if (needsUpdate) {
            updateCamera(existing.id, {
              parent_joint: mount.parentJoint,
              pose: mount.pose,
              intrinsics: defaultIntrinsics,
            });
          }
          return;
        }
        addCamera({
          name: mount.name,
          parent_joint: mount.parentJoint,
          pose: mount.pose,
          intrinsics: defaultIntrinsics,
        });
      });

      normalizedRetainedCameras.forEach((camera) => {
        if (!isAutoGeneratedCameraName(camera.name)) return;
        if (desiredNames.has(camera.name)) return;
        removeCamera(camera.id);
      });

      return normalizedRetainedCameras.length + stableMounts.length > 0;
    },
    [
      addCamera,
      availableLinks.length,
      effectiveLoadSignature,
      removeCamera,
      resolveCameraPrefixMounts,
      robot,
      setBootstrapState,
      thumbnailMode,
      updateCamera,
    ]
  );

  const hasPendingAutoCameraGeometry = useCallback(
    () => hasPendingAutoCameraGeometryRef.current,
    []
  );

  return {
    autoCameraBootstrapState,
    ensureDetectedCamerasForLoadedRobot,
    hasPendingAutoCameraGeometry,
  };
};
