from __future__ import annotations

import struct

STREAM_FRAME_HEADER_FORMAT = "<IIQQII"
STREAM_FRAME_HEADER_BYTES = struct.calcsize(STREAM_FRAME_HEADER_FORMAT)

STREAM_SEQUENCE_START = 1
STREAM_SEQUENCE_STEP = 1
STREAM_FLAGS_NONE = 0
STREAM_FLAG_PAYLOAD_JSON = 1 << 0
STREAM_FLAG_PAYLOAD_FLATBUFFER = 1 << 1
STREAM_MAX_PAYLOAD_BYTES = 8 * 1024 * 1024

STREAM_SEND_INTERVAL_SEC = 0.25
STREAM_TICK_INTERVAL_NS = 50_000_000

ROSVIZ_SESSION_ID_PREFIX = "rosviz"
ROSVIZ_SESSION_ID_HEX_LENGTH = 12
ROSVIZ_STREAM_SUBPROTOCOL = "urdf-studio.rosviz.v1"
ROSVIZ_STREAM_TICKET_SUBPROTOCOL_PREFIX = "ticket."
ROSVIZ_STREAM_TICKET_BYTES = 16
ROSVIZ_STREAM_TICKET_TTL_MS = 5_000
ROSVIZ_STREAM_TICKET_MAX_ACTIVE_PER_SESSION = 4

DEFAULT_FIXED_FRAME = "map"
DEFAULT_ROBOT_ID = "robot_0"
DEFAULT_DETERMINISTIC_MODE = "strict"
DETERMINISTIC_STRICT_EPOCH_NS = 0

TOPIC_ID_TF_EDGE_BATCH = 1
TOPIC_ID_RESOLVED_FRAME_POSE_BATCH = 2
TOPIC_ID_MARKER_DELTA_BATCH = 3
TOPIC_ID_POINTCLOUD_CHUNK = 4
TOPIC_ID_JOINT_STATE_BATCH = 5
TOPIC_ID_CLOCK_TICK = 6
TOPIC_ID_DIAGNOSTIC_EVENT = 7

DEFAULT_SUBSCRIBED_TOPIC_IDS = (
    TOPIC_ID_RESOLVED_FRAME_POSE_BATCH,
    TOPIC_ID_CLOCK_TICK,
    TOPIC_ID_DIAGNOSTIC_EVENT,
)

DEFAULT_DIAGNOSTIC_CODE = "ros_viz_stream_active"
DEFAULT_CLOCK_MODE = "live"
DEFAULT_PLAYBACK_RATE = 1.0
MIN_PLAYBACK_RATE = 0.1
MAX_PLAYBACK_RATE = 8.0
MAX_CLOCK_STEP_TICKS = 10_000
DEFAULT_FRAME_ID_BASE_LINK = "base_link"
DEFAULT_FRAME_ID_TOOL0 = "tool0"
DEFAULT_PARENT_WORLD = "world"
DEFAULT_PARENT_BASE = DEFAULT_FRAME_ID_BASE_LINK
DEFAULT_FRAME_ID_ELBOW = "elbow_link"

MARKER_NS_TRAJECTORY = "trajectory"
MARKER_NS_STATUS = "status"
MARKER_ID_TRAJECTORY_LINE = 1
MARKER_ID_TOOL_SPHERE = 2
MARKER_ID_ALERT = 3
MARKER_TRAJECTORY_MAX_POINTS = 80
MARKER_ALERT_PERIOD_TICKS = 60
MARKER_ALERT_LIFETIME_MS = 900

MAX_TOPIC_SUBSCRIPTIONS = 128
