// Studio-local boundary over the public i-love-urdf package.
// Private runtime code should import from here instead of reaching into i-love-urdf directly.

export {
  analyzeUrdf,
  autoFitCollisionGeometry,
  buildDependencyRepositoryNameCandidates,
  buildPackageRootsFromRepositoryFiles,
  buildXacroExpandRequestPayload,
  collectMeshReferencedPackageNamesFromUrdf,
  collectPackageNamesFromText,
  collectPackageResourceFilesForMatchedFiles,
  collectPackageResourceFilesForReferencedPackages,
  collectXacroSupportFilesFromRepository,
  createXacroFilePayloadFromBytes,
  describeSupportedMeshExtensions,
  extractMeshReferencesFromUrdf,
  findPackageXmlForPackageName,
  findRepositoryUrdfCandidates,
  getMeshSupportStatus,
  hasRenderableUrdfGeometry,
  hasXacroSyntax,
  inspectRepositoryCandidates,
  isSupportedMeshExtension,
  isUrdfXacroPath,
  isXacroPath,
  isXacroSupportPath,
  normalizeExpandedUrdfPath,
  normalizeRepositoryPath,
  parseXacroExpandResponsePayload,
  repositoryContainsPackage,
  repositoryDirname,
  resolveMeshPathInRepository,
  resolveRepositoryMeshReferences,
  resolveRepositoryXacroTargetPath,
  SUPPORTED_MESH_EXTENSIONS,
  type CollisionAutoFitResult,
  type CollisionAutoFitType,
  type RepositoryUrdfCandidate,
  updateMeshPathsToAssetsInUrdf,
  type XacroExpandResponsePayload,
  type XacroFilePayload,
} from "i-love-urdf";

export {
  computeMeshBoundsFromArrayBuffer,
  normalizeMeshPathForMatch,
  resolveMeshCandidates,
  resolveMeshResourceBlob,
  type OriginData,
} from "i-love-urdf/browser";
