export const URDF_ANIMATION_FRAME_PRIORITY = -20;
export const PLAYBACK_BASE_POSE_TRANSLATION_EPSILON_METERS = 5e-4;
export const PLAYBACK_BASE_POSE_ROTATION_EPSILON_RAD = 5e-4;
export const PLAYBACK_MAX_WALL_CLOCK_STEP_MS = 100;
export const PLAYBACK_JOINT_STORE_SYNC_INTERVAL_MS = 80;
