export const INERTIAL_DIAGNOSTICS_NEAR_MISS_EIGENVALUE_EPS = 1e-6;
export const INERTIAL_DIAGNOSTICS_NEAR_MISS_TRIANGLE_GAP_EPS = 1e-6;
export const INERTIAL_DIAGNOSTICS_ILL_CONDITIONED_RATIO = 1e4;
export const INERTIAL_DIAGNOSTICS_PSD_EIGENVALUE_EPS = 1e-6;
export const INERTIAL_DIAGNOSTICS_PSD_TRIANGLE_MARGIN_EPS = 1e-6;
