export const MESH_SANITIZER_MIN_COMPONENT_VOLUME_RATIO = 0.05;
export const MESH_SANITIZER_MAX_TOTAL_DELETION_RATIO = 0.05;
export const MESH_SANITIZER_VERTEX_KEY_DECIMALS = 9;
export const MESH_SANITIZER_MAX_COM_SHIFT_CHARACTERISTIC_LENGTH_RATIO = 0.01;
export const MESH_SANITIZER_MAX_MASS_LOSS_RATIO = 0.001;
export const MESH_SANITIZER_SIGNIFICANT_MASS_LOSS_RATIO = 0.001;
export const MESH_SANITIZER_MAX_INERTIA_TRACE_CHANGE_RATIO = 0.001;
export const MESH_SANITIZER_MAX_PHYSICS_IMPACT_RATIO = 0.001;
