export const REPEATED_INERTIA_MIN_INSTANCE_COUNT = 2;
export const REPEATED_INERTIA_RELATIVE_SPREAD_EPSILON = 1e-12;
export const REPEATED_INERTIA_MASS_RELATIVE_TOLERANCE = 1e-4;
export const REPEATED_INERTIA_PRINCIPAL_MOMENT_RELATIVE_TOLERANCE = 1e-3;
export const REPEATED_INERTIA_MESH_LOCAL_COM_TOLERANCE_METERS = 5e-4;

export const REPEATED_INERTIA_CANONICALIZATION_MAX_MASS_RELATIVE_SPREAD = 1e-2;
export const REPEATED_INERTIA_CANONICALIZATION_MAX_PRINCIPAL_RELATIVE_SPREAD = 1e-2;
export const REPEATED_INERTIA_CANONICALIZATION_MAX_MESH_LOCAL_COM_SEPARATION_METERS = 2e-3;

export const REPEATED_INERTIA_MANUAL_FIX_ALREADY_CONSISTENT_MAX_MASS_RELATIVE_SPREAD = 1e-9;
export const REPEATED_INERTIA_MANUAL_FIX_ALREADY_CONSISTENT_MAX_PRINCIPAL_RELATIVE_SPREAD = 1e-9;
export const REPEATED_INERTIA_MANUAL_FIX_ALREADY_CONSISTENT_MAX_MESH_LOCAL_COM_SEPARATION_METERS = 1e-9;
