export {
  REPEATED_INERTIA_MASS_RELATIVE_TOLERANCE,
  REPEATED_INERTIA_MESH_LOCAL_COM_TOLERANCE_METERS,
  REPEATED_INERTIA_MIN_INSTANCE_COUNT,
  REPEATED_INERTIA_PRINCIPAL_MOMENT_RELATIVE_TOLERANCE,
  REPEATED_INERTIA_RELATIVE_SPREAD_EPSILON,
} from "@/features/urdf/inertia/repeatedInertiaParams";
