export const ROBOT_MIRROR_SYMMETRY_MAX_PAIR_RESIDUAL_METERS = 0.01;
export const ROBOT_MIRROR_SYMMETRY_MAX_CENTER_DISTANCE_METERS = 0.005;
export const ROBOT_MIRROR_SYMMETRY_PLANE_TOUCH_TOLERANCE_METERS = 0.001;
export const ROBOT_MIRROR_SYMMETRY_MIN_MATCHED_PAIR_COUNT = 1;
export const ROBOT_MIRROR_SYMMETRY_MIN_SUPPORTED_LINK_COUNT = 4;
export const ROBOT_MIRROR_SYMMETRY_MIN_SUPPORTED_GROUP_COUNT = 2;
export const ROBOT_MIRROR_SYMMETRY_REPAIR_MIN_STEP_METERS = 0.0005;
export const ROBOT_MIRROR_SYMMETRY_REPAIR_MIN_STEP_RADIANS = Math.PI / 180;
export const ROBOT_MIRROR_SYMMETRY_MAX_AUTO_ORIENTATION_DELTA_RADIANS = Math.PI / 6;
export const ROBOT_MIRROR_SYMMETRY_MIN_AUTO_ORIENTATION_GAP_RADIANS = Math.PI / 36;
export const ROBOT_MIRROR_MESH_SCALE_COMPONENT_COUNT = 3;
export const ROBOT_MIRROR_MESH_SCALE_DEFAULT_COMPONENT = 1;
export const ROBOT_MIRROR_INERTIAL_CENTER_REPAIR_MIN_STEP_METERS = 0.0005;
export const ROBOT_MIRROR_SYMMETRY_REPAIR_MAX_VALIDATION_RESIDUAL_METERS = Math.max(
  ROBOT_MIRROR_SYMMETRY_MAX_PAIR_RESIDUAL_METERS,
  ROBOT_MIRROR_SYMMETRY_MAX_CENTER_DISTANCE_METERS
);
