export const KINEMATIC_SYNTHESIS_PREVIEW_SAMPLE_LIMIT = 3 as const;
export const KINEMATIC_SYNTHESIS_SUPPORT_PLANE_BAND_RATIO = 0.02 as const;
export const KINEMATIC_SYNTHESIS_SUPPORT_PLANE_BAND_MIN_M = 0.005 as const;
export const KINEMATIC_SYNTHESIS_SUPPORT_PLANE_MIN_VERTICES = 4 as const;
export const KINEMATIC_SYNTHESIS_SUPPORT_PLANE_MIN_MESHES = 1 as const;
export const KINEMATIC_SYNTHESIS_SUPPORT_PLANE_MIN_CONFIDENCE = 0.1 as const;
