export const COLLABORATION_SHARE_SCOPE_PARAMS = {
  tailscaleCgnatFirstOctet: 100,
  tailscaleCgnatSecondOctetMin: 64,
  tailscaleCgnatSecondOctetMax: 127,
  rfc1918TenFirstOctet: 10,
  rfc1918OneSeventyTwoFirstOctet: 172,
  rfc1918OneSeventyTwoSecondOctetMin: 16,
  rfc1918OneSeventyTwoSecondOctetMax: 31,
  rfc1918OneNinetyTwoFirstOctet: 192,
  rfc1918OneNinetyTwoSecondOctet: 168,
  loopbackIpv4FirstOctet: 127,
  ipv4OctetCount: 4,
  ipv4OctetMin: 0,
  ipv4OctetMax: 255,
  localhostHostname: "localhost",
  ipv6LoopbackHostname: "::1",
  allInterfacesIpv4Host: "0.0.0.0",
  tailnetDnsSuffix: ".ts.net",
  lanMdnsSuffix: ".local",
  fallbackScope: {
    kind: "local",
    badgeLabel: "Local only",
    description: "Share links need a valid Studio URL before they can be sent.",
    canEmail: false,
  },
  loopbackScope: {
    kind: "local",
    badgeLabel: "Local only",
    description: "Remote sharing is off for this session. Local links only open on this machine.",
    canEmail: false,
  },
  tailnetScope: {
    kind: "tailnet",
    badgeLabel: "Tailnet",
    description: "This link works only for devices allowed into your Tailscale Tailnet.",
    canEmail: true,
  },
  lanScope: {
    kind: "lan",
    badgeLabel: "Local network",
    description: "This link works only for devices on this LAN or Wi-Fi network.",
    canEmail: true,
  },
  publicScope: {
    kind: "public",
    badgeLabel: "Public URL",
    description: "This link uses a public hostname. Use it only if that exposure is approved.",
    canEmail: true,
  },
} as const;
