import type { DataZeroJointSource } from "@/shared/store/useJointStore";

export const HF_DATASET_DEFAULT_FPS = 30;
export const HF_DATASET_TARGET_ZERO_SOURCE: DataZeroJointSource = "auto";
export const HF_DATASET_ROWS_BATCH_SIZE = 100;
export const HF_DATASET_FIRST_EPISODE_FETCH_MAX_ATTEMPTS = 10;
export const HF_DATASET_FIRST_EPISODE_FETCH_BASE_DELAY_MS = 500;
export const HF_DATASET_FIRST_EPISODE_FETCH_INTER_BATCH_DELAY_MS = 20;
export const HF_DATASET_INDEX_CHUNK_EPISODES = 10;
export const HF_DATASET_INDEX_RUNTIME_MS = 9000;
export const HF_DATASET_INDEX_MAX_FAILED_BATCHES = 4;
export const HF_DATASET_INDEX_MAX_DEFERRED_RETRIES = 1;
export const HF_DATASET_INDEX_FETCH_MAX_ATTEMPTS = 3;
export const HF_DATASET_INDEX_FETCH_BASE_DELAY_MS = 220;
export const HF_DATASET_INDEX_FETCH_MAX_DELAY_MS = 900;
export const HF_DATASET_INDEX_DEFERRED_RETRY_DELAY_MS = 12;
export const HF_DATASET_INDEX_INTER_BATCH_DELAY_MS = 15;
export const HF_DATASET_INDEX_PROGRESS_EMIT_INTERVAL = 4;
export const HF_DATASET_INDEX_PROGRESS_TOTAL_SYNC_INTERVAL = 8;

export const HF_LAZY_EPISODE_FETCH_RUNTIME_MS = 9000;
export const HF_LAZY_EPISODE_FETCH_MAX_FAILED_WINDOWS = 3;
export const HF_LAZY_EPISODE_FETCH_RETRY_MAX_ATTEMPTS = 2;
export const HF_LAZY_EPISODE_FETCH_RETRY_BASE_DELAY_MS = 180;
export const HF_LAZY_EPISODE_FETCH_RETRY_MAX_DELAY_MS = 700;
export const HF_LAZY_EPISODE_FETCH_INTER_WINDOW_DELAY_MS = 12;
export const HF_LAZY_EPISODE_FETCH_MAX_CONCURRENT_WINDOWS = 3;
export const HF_LAZY_EPISODE_WORKER_MIN_ROWS = 180;
export const HF_LAZY_EPISODE_CACHE_LIMIT = 6;
