import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ExternalLink,
  Loader2,
  PackageOpen,
  RefreshCw,
  Sparkles,
  UploadCloud,
} from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/shared/ui/button";
import { Badge } from "@/shared/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/shared/ui/dialog";
import type { FeatureGate } from "@/shared/config/featureGates";
import type { FeatureGateAvailability } from "@/shared/lib/featureGateUi";
import { getFeatureGateUiState } from "@/shared/lib/featureGateUi";
import {
  generateWorldLabsWorld,
  getWorldLabsCapabilities,
  getWorldLabsOperation,
} from "@/features/world-share/worldLabsApi";
import type {
  WorldLabsCapabilitiesResponse,
  WorldLabsOperationStatusResponse,
} from "@/features/world-share/worldLabsTypes";
import type {
  WorldScenePackageListEntry,
  WorldScenePackageManifest,
} from "@/features/world-share/worldScenePackageTypes";

type WorldRegistryPanelProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  entries: WorldScenePackageListEntry[];
  filterText: string;
  onFilterTextChange: (value: string) => void;
  loading: boolean;
  onRefresh: () => void;
  onLoadPackage: (entry: WorldScenePackageListEntry) => void;
  onLoadGeneratedWorldPackage: (manifest: WorldScenePackageManifest) => void;
  onPublishGeneratedWorldPackage?: (manifest: WorldScenePackageManifest) => Promise<void> | void;
  gate?: FeatureGate | FeatureGateAvailability;
};

const WORLD_LABS_PANEL_PARAMS = {
  pollIntervalMs: 2500,
  maxPolls: 120,
  defaultPrompt:
    "Generate a metric robot warehouse test scene with dock doors, pallets, robot lanes, clear ground plane, and collider-friendly geometry.",
  defaultDisplayName: "Robot warehouse generated by World Labs",
  defaultModel: "marble-1.0",
  defaultTags: "wsp,robotics,world-model",
  maxSeed: 4294967295,
} as const;

const TRUST_BADGE_CLASS_BY_LEVEL = {
  metadata_complete: "bg-emerald-600/20 text-emerald-300 border-emerald-500/40",
  signed_metadata: "bg-amber-500/20 text-amber-200 border-amber-400/40",
  metadata_only: "bg-zinc-700/50 text-zinc-300 border-zinc-500/40",
} as const;

type TrustLevel = keyof typeof TRUST_BADGE_CLASS_BY_LEVEL;
const DEFAULT_TRUST_LEVEL: TrustLevel = "metadata_only";

const TRUST_LABEL_BY_LEVEL: Record<TrustLevel, string> = {
  metadata_complete: "metadata-complete",
  signed_metadata: "signed-metadata",
  metadata_only: "metadata-only",
};

const resolveTrustLevel = (trustLevel: string): TrustLevel => {
  if (trustLevel in TRUST_BADGE_CLASS_BY_LEVEL) {
    return trustLevel as TrustLevel;
  }
  return DEFAULT_TRUST_LEVEL;
};

const formatTimestamp = (iso: string) => {
  const parsed = new Date(iso);
  if (Number.isNaN(parsed.getTime())) return iso;
  return parsed.toLocaleString();
};

const normalizeWorldLabsTags = (rawTags: string) =>
  rawTags
    .split(",")
    .map((tag) => tag.trim())
    .filter(Boolean)
    .slice(0, 10);

const parseWorldLabsSeed = (seedText: string): number | null => {
  const normalized = seedText.trim();
  if (!normalized) return null;
  const seed = Number(normalized);
  if (!Number.isInteger(seed) || seed < 0 || seed > WORLD_LABS_PANEL_PARAMS.maxSeed) {
    throw new Error(`Seed must be an integer from 0 to ${WORLD_LABS_PANEL_PARAMS.maxSeed}.`);
  }
  return seed;
};

const formatWorldLabsMetric = (value?: number | null) =>
  typeof value === "number" && Number.isFinite(value) ? value.toFixed(3) : "n/a";

const resolveWorldLabsProgress = (operation: WorldLabsOperationStatusResponse | null) => {
  const progress = operation?.metadata.progress;
  if (typeof progress !== "number" || !Number.isFinite(progress)) return null;
  return progress <= 1 ? Math.round(progress * 100) : Math.round(progress);
};

export const WorldRegistryPanel = ({
  open,
  onOpenChange,
  entries,
  filterText,
  onFilterTextChange,
  loading,
  onRefresh,
  onLoadPackage,
  onLoadGeneratedWorldPackage,
  onPublishGeneratedWorldPackage,
  gate,
}: WorldRegistryPanelProps) => {
  const refreshGateUi = gate
    ? getFeatureGateUiState("Refresh", gate)
    : { label: "Refresh", disabled: false, title: undefined };
  const loadGateUi = gate
    ? getFeatureGateUiState("Load", gate)
    : { label: "Load", disabled: false, title: undefined };
  const normalizedFilter = filterText.trim().toLowerCase();
  const filteredEntries = useMemo(() => {
    if (!normalizedFilter) return entries;
    return entries.filter((entry) => {
      const runtimeTargets = entry.runtime_targets.join(" ").toLowerCase();
      return (
        entry.package_id.toLowerCase().includes(normalizedFilter) ||
        entry.title.toLowerCase().includes(normalizedFilter) ||
        entry.latest_version.toLowerCase().includes(normalizedFilter) ||
        runtimeTargets.includes(normalizedFilter)
      );
    });
  }, [entries, normalizedFilter]);

  const [worldLabsCapabilities, setWorldLabsCapabilities] =
    useState<WorldLabsCapabilitiesResponse | null>(null);
  const [worldLabsCapabilitiesLoading, setWorldLabsCapabilitiesLoading] = useState(false);
  const [worldLabsPrompt, setWorldLabsPrompt] = useState<string>(
    WORLD_LABS_PANEL_PARAMS.defaultPrompt
  );
  const [worldLabsDisplayName, setWorldLabsDisplayName] = useState<string>(
    WORLD_LABS_PANEL_PARAMS.defaultDisplayName
  );
  const [worldLabsModel, setWorldLabsModel] = useState<string>(
    WORLD_LABS_PANEL_PARAMS.defaultModel
  );
  const [worldLabsSeedText, setWorldLabsSeedText] = useState("");
  const [worldLabsTagsText, setWorldLabsTagsText] = useState<string>(
    WORLD_LABS_PANEL_PARAMS.defaultTags
  );
  const [worldLabsPublic, setWorldLabsPublic] = useState(false);
  const [worldLabsError, setWorldLabsError] = useState<string | null>(null);
  const [worldLabsGenerating, setWorldLabsGenerating] = useState(false);
  const [worldLabsPolling, setWorldLabsPolling] = useState(false);
  const [worldLabsPublishing, setWorldLabsPublishing] = useState(false);
  const [worldLabsOperation, setWorldLabsOperation] =
    useState<WorldLabsOperationStatusResponse | null>(null);
  const [generatedWorldPackage, setGeneratedWorldPackage] =
    useState<WorldScenePackageManifest | null>(null);
  const worldLabsPollTimeoutRef = useRef<number | null>(null);
  const worldLabsPollCountRef = useRef(0);

  const clearWorldLabsPoll = useCallback(() => {
    if (worldLabsPollTimeoutRef.current !== null) {
      window.clearTimeout(worldLabsPollTimeoutRef.current);
      worldLabsPollTimeoutRef.current = null;
    }
  }, []);

  const loadWorldLabsCapabilities = useCallback(async () => {
    setWorldLabsCapabilitiesLoading(true);
    try {
      const capabilities = await getWorldLabsCapabilities();
      setWorldLabsCapabilities(capabilities);
      setWorldLabsModel((current) => {
        if (capabilities.models.includes(current)) return current;
        return (
          capabilities.default_model ||
          capabilities.models[0] ||
          WORLD_LABS_PANEL_PARAMS.defaultModel
        );
      });
      setWorldLabsError((current) => current && !capabilities.configured ? current : null);
    } catch (error) {
      setWorldLabsError(
        error instanceof Error ? error.message : "World Labs capabilities unavailable"
      );
    } finally {
      setWorldLabsCapabilitiesLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!open) {
      clearWorldLabsPoll();
      return;
    }
    void loadWorldLabsCapabilities();
  }, [clearWorldLabsPoll, loadWorldLabsCapabilities, open]);

  useEffect(() => () => clearWorldLabsPoll(), [clearWorldLabsPoll]);

  const pollWorldLabsOperation = useCallback(
    (operationId: string) => {
      clearWorldLabsPoll();
      worldLabsPollCountRef.current = 0;
      setWorldLabsPolling(true);

      const runPoll = async () => {
        try {
          worldLabsPollCountRef.current += 1;
          const status = await getWorldLabsOperation(operationId);
          setWorldLabsOperation(status);
          if (status.error) {
            setWorldLabsPolling(false);
            setWorldLabsError(JSON.stringify(status.error));
            return;
          }
          if (status.done) {
            setWorldLabsPolling(false);
            setGeneratedWorldPackage(status.world_package ?? null);
            if (status.world_package) {
              toast.success(`World Labs package ready: ${status.world_package.package_id}`);
            }
            return;
          }
          if (worldLabsPollCountRef.current >= WORLD_LABS_PANEL_PARAMS.maxPolls) {
            setWorldLabsPolling(false);
            setWorldLabsError("World Labs generation is still running. Reopen the operation later.");
            return;
          }
          worldLabsPollTimeoutRef.current = window.setTimeout(
            () => void runPoll(),
            WORLD_LABS_PANEL_PARAMS.pollIntervalMs
          );
        } catch (error) {
          setWorldLabsPolling(false);
          setWorldLabsError(
            error instanceof Error ? error.message : "World Labs operation polling failed"
          );
        }
      };

      void runPoll();
    },
    [clearWorldLabsPoll]
  );

  const handleGenerateWorldLabsWorld = useCallback(async () => {
    if (worldLabsCapabilities && !worldLabsCapabilities.configured) {
      setWorldLabsError(
        worldLabsCapabilities.missing_reason || "WORLD_LABS_API_KEY is not configured on the backend."
      );
      return;
    }
    const prompt = worldLabsPrompt.trim();
    const displayName = worldLabsDisplayName.trim();
    if (!prompt || !displayName) {
      setWorldLabsError("Prompt and display name are required.");
      return;
    }

    setWorldLabsGenerating(true);
    setWorldLabsError(null);
    setGeneratedWorldPackage(null);
    setWorldLabsOperation(null);
    clearWorldLabsPoll();

    try {
      const seed = parseWorldLabsSeed(worldLabsSeedText);
      const operation = await generateWorldLabsWorld({
        prompt,
        display_name: displayName,
        model: worldLabsModel,
        seed,
        tags: normalizeWorldLabsTags(worldLabsTagsText),
        public: worldLabsPublic,
        allow_id_access: true,
        disable_recaption: true,
      });
      setWorldLabsOperation({
        operation_id: operation.operation_id,
        done: false,
        metadata: {},
        raw_response: operation.raw_response,
      });
      pollWorldLabsOperation(operation.operation_id);
    } catch (error) {
      setWorldLabsError(error instanceof Error ? error.message : "World Labs generation failed");
    } finally {
      setWorldLabsGenerating(false);
    }
  }, [
    clearWorldLabsPoll,
    pollWorldLabsOperation,
    worldLabsCapabilities,
    worldLabsDisplayName,
    worldLabsModel,
    worldLabsPrompt,
    worldLabsPublic,
    worldLabsSeedText,
    worldLabsTagsText,
  ]);

  const handlePublishGeneratedWorldPackage = useCallback(async () => {
    if (!generatedWorldPackage || !onPublishGeneratedWorldPackage) return;
    setWorldLabsPublishing(true);
    setWorldLabsError(null);
    try {
      await onPublishGeneratedWorldPackage(generatedWorldPackage);
    } catch (error) {
      setWorldLabsError(
        error instanceof Error ? error.message : "Failed to publish generated world package"
      );
    } finally {
      setWorldLabsPublishing(false);
    }
  }, [generatedWorldPackage, onPublishGeneratedWorldPackage]);

  const worldLabsConfigured = worldLabsCapabilities?.configured === true;
  const worldLabsModels = worldLabsCapabilities?.models.length
    ? worldLabsCapabilities.models
    : [WORLD_LABS_PANEL_PARAMS.defaultModel];
  const worldLabsProgress = resolveWorldLabsProgress(worldLabsOperation);
  const marbleUrl = worldLabsOperation?.world_marble_url || worldLabsCapabilities?.marble_url;
  const thumbnailUrl = worldLabsOperation?.thumbnail_url || undefined;
  const worldLabsGenerateDisabled =
    worldLabsGenerating || worldLabsPolling || worldLabsCapabilitiesLoading || !worldLabsConfigured;
  const canPublishGeneratedPackage =
    Boolean(generatedWorldPackage && onPublishGeneratedWorldPackage) && !worldLabsPublishing;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[92vh] max-w-7xl overflow-hidden border-[#3d3d3d] bg-[#1f1f1f] text-[#d4d4d4]">
        <DialogHeader>
          <DialogTitle className="text-[#f0f0f0]">Worlds</DialogTitle>
          <DialogDescription className="text-[#a8a8a8]">
            Generate World Labs worlds and browse published world packages.
          </DialogDescription>
          {gate && !gate.enabled ? (
            <DialogDescription className="text-amber-500">
              {gate.disabledBadge}
            </DialogDescription>
          ) : null}
        </DialogHeader>

        <div className="max-h-[78vh] space-y-4 overflow-auto pr-1">
          <section className="rounded-md border border-[#3d3d3d] bg-[#232323] p-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <div className="flex min-w-0 items-center gap-2">
                <Sparkles className="h-4 w-4 text-cyan-300" />
                <div>
                  <div className="text-sm font-medium text-[#f0f0f0]">World Labs Marble</div>
                  <div className="text-xs text-[#9e9e9e]">
                    Generated worlds import as WSP candidate packages.
                  </div>
                </div>
                <Badge
                  variant="outline"
                  className={
                    worldLabsConfigured
                      ? "border-emerald-500/40 bg-emerald-600/20 text-emerald-300"
                      : "border-amber-400/40 bg-amber-500/20 text-amber-200"
                  }
                >
                  {worldLabsCapabilitiesLoading
                    ? "checking"
                    : worldLabsConfigured
                      ? "backend-configured"
                      : "backend-missing-key"}
                </Badge>
              </div>
              <div className="flex items-center gap-2">
                {worldLabsCapabilities?.docs_url ? (
                  <Button
                    type="button"
                    asChild
                    size="sm"
                    variant="outline"
                    className="h-8 border-[#3d3d3d] bg-[#252526] text-[#d4d4d4] hover:bg-[#323233] hover:text-white"
                  >
                    <a href={worldLabsCapabilities.docs_url} target="_blank" rel="noreferrer">
                      <ExternalLink />
                      API docs
                    </a>
                  </Button>
                ) : null}
                {worldLabsCapabilities?.marble_url ? (
                  <Button
                    type="button"
                    asChild
                    size="sm"
                    variant="outline"
                    className="h-8 border-[#3d3d3d] bg-[#252526] text-[#d4d4d4] hover:bg-[#323233] hover:text-white"
                  >
                    <a href={worldLabsCapabilities.marble_url} target="_blank" rel="noreferrer">
                      <ExternalLink />
                      Marble
                    </a>
                  </Button>
                ) : null}
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  className="h-8 border-[#3d3d3d] bg-[#252526] text-[#d4d4d4] hover:bg-[#323233] hover:text-white"
                  onClick={() => void loadWorldLabsCapabilities()}
                  disabled={worldLabsCapabilitiesLoading}
                >
                  {worldLabsCapabilitiesLoading ? (
                    <Loader2 className="animate-spin" />
                  ) : (
                    <RefreshCw />
                  )}
                  Status
                </Button>
              </div>
            </div>

            {worldLabsError ? (
              <div className="mt-3 rounded-md border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-xs text-amber-200">
                {worldLabsError}
              </div>
            ) : null}

            <div className="mt-3 grid gap-3 lg:grid-cols-[minmax(0,1fr)_320px]">
              <label className="block text-xs text-[#bdbdbd]">
                Prompt
                <textarea
                  value={worldLabsPrompt}
                  onChange={(event) => setWorldLabsPrompt(event.target.value)}
                  className="mt-1 min-h-[112px] w-full resize-y rounded-md border border-[#3d3d3d] bg-[#252526] px-3 py-2 text-sm text-[#e2e2e2] outline-none focus:border-[#5a5a5a]"
                  maxLength={2500}
                />
              </label>

              <div className="grid gap-2">
                <label className="block text-xs text-[#bdbdbd]">
                  Display name
                  <input
                    value={worldLabsDisplayName}
                    onChange={(event) => setWorldLabsDisplayName(event.target.value)}
                    className="mt-1 h-9 w-full rounded-md border border-[#3d3d3d] bg-[#252526] px-3 text-sm text-[#e2e2e2] outline-none focus:border-[#5a5a5a]"
                    maxLength={64}
                  />
                </label>
                <label className="block text-xs text-[#bdbdbd]">
                  Model
                  <select
                    value={worldLabsModel}
                    onChange={(event) => setWorldLabsModel(event.target.value)}
                    className="mt-1 h-9 w-full rounded-md border border-[#3d3d3d] bg-[#252526] px-3 text-sm text-[#e2e2e2] outline-none focus:border-[#5a5a5a]"
                  >
                    {worldLabsModels.map((model) => (
                      <option key={model} value={model}>
                        {model}
                      </option>
                    ))}
                  </select>
                </label>
                <div className="grid grid-cols-[minmax(0,1fr)_112px] gap-2">
                  <label className="block text-xs text-[#bdbdbd]">
                    Tags
                    <input
                      value={worldLabsTagsText}
                      onChange={(event) => setWorldLabsTagsText(event.target.value)}
                      className="mt-1 h-9 w-full rounded-md border border-[#3d3d3d] bg-[#252526] px-3 text-sm text-[#e2e2e2] outline-none focus:border-[#5a5a5a]"
                    />
                  </label>
                  <label className="block text-xs text-[#bdbdbd]">
                    Seed
                    <input
                      value={worldLabsSeedText}
                      onChange={(event) => setWorldLabsSeedText(event.target.value)}
                      inputMode="numeric"
                      className="mt-1 h-9 w-full rounded-md border border-[#3d3d3d] bg-[#252526] px-3 text-sm text-[#e2e2e2] outline-none focus:border-[#5a5a5a]"
                    />
                  </label>
                </div>
                <label className="flex items-center gap-2 text-xs text-[#bdbdbd]">
                  <input
                    type="checkbox"
                    checked={worldLabsPublic}
                    onChange={(event) => setWorldLabsPublic(event.target.checked)}
                    className="h-4 w-4 rounded border-[#4d4d4d] bg-[#252526]"
                  />
                  Public World Labs world
                </label>
                <Button
                  type="button"
                  className="h-9 bg-cyan-500 text-slate-950 hover:bg-cyan-400"
                  onClick={() => void handleGenerateWorldLabsWorld()}
                  disabled={worldLabsGenerateDisabled}
                  title={
                    worldLabsConfigured
                      ? undefined
                      : worldLabsCapabilities?.missing_reason ||
                        "Configure WORLD_LABS_API_KEY on the backend."
                  }
                >
                  {worldLabsGenerating || worldLabsPolling ? (
                    <Loader2 className="animate-spin" />
                  ) : (
                    <Sparkles />
                  )}
                  {worldLabsPolling ? "Generating..." : "Generate world"}
                </Button>
              </div>
            </div>

            {worldLabsOperation ? (
              <div className="mt-3 rounded-md border border-[#353535] bg-[#1f1f1f] p-3">
                <div className="flex flex-wrap items-center justify-between gap-2 text-xs">
                  <div className="min-w-0">
                    <div className="font-medium text-[#f2f2f2]">
                      Operation {worldLabsOperation.operation_id}
                    </div>
                    <div className="text-[#9e9e9e]">
                      {worldLabsOperation.done
                        ? "complete"
                        : worldLabsPolling
                          ? "running"
                          : "pending"}
                      {worldLabsProgress !== null ? ` · ${worldLabsProgress}%` : ""}
                    </div>
                  </div>
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge
                      variant="outline"
                      className={
                        worldLabsOperation.done
                          ? "border-emerald-500/40 bg-emerald-600/20 text-emerald-300"
                          : "border-cyan-500/40 bg-cyan-500/10 text-cyan-200"
                      }
                    >
                      {worldLabsOperation.done ? "wsp-ready" : "polling"}
                    </Badge>
                    {marbleUrl ? (
                      <Button
                        type="button"
                        asChild
                        size="sm"
                        variant="outline"
                        className="h-8 border-[#3d3d3d] bg-[#252526] text-[#d4d4d4] hover:bg-[#323233] hover:text-white"
                      >
                        <a href={marbleUrl} target="_blank" rel="noreferrer">
                          <ExternalLink />
                          Open
                        </a>
                      </Button>
                    ) : null}
                  </div>
                </div>

                {generatedWorldPackage ? (
                  <div className="mt-3 grid gap-3 md:grid-cols-[220px_minmax(0,1fr)]">
                    <div className="aspect-video overflow-hidden rounded-md border border-[#353535] bg-[#151515]">
                      {thumbnailUrl ? (
                        <img
                          src={thumbnailUrl}
                          alt={generatedWorldPackage.title}
                          className="h-full w-full object-cover"
                        />
                      ) : (
                        <div className="flex h-full items-center justify-center text-xs text-[#8f8f8f]">
                          No thumbnail
                        </div>
                      )}
                    </div>
                    <div className="min-w-0">
                      <div className="truncate text-sm font-medium text-[#f2f2f2]">
                        {generatedWorldPackage.title}
                      </div>
                      <div className="mt-1 text-xs text-[#9e9e9e]">
                        {generatedWorldPackage.package_id}@{generatedWorldPackage.version}
                      </div>
                      <div className="mt-2 grid gap-1 text-xs text-[#c9c9c9] sm:grid-cols-3">
                        <div>scale {formatWorldLabsMetric(worldLabsOperation.metric_scale_factor)}</div>
                        <div>ground {formatWorldLabsMetric(worldLabsOperation.ground_plane_offset)}</div>
                        <div>{generatedWorldPackage.artifacts.length} artifacts</div>
                      </div>
                      <div className="mt-3 flex flex-wrap gap-2">
                        <Button
                          type="button"
                          size="sm"
                          className="h-8 bg-emerald-500 text-slate-950 hover:bg-emerald-400"
                          onClick={() => onLoadGeneratedWorldPackage(generatedWorldPackage)}
                        >
                          <PackageOpen />
                          Load package
                        </Button>
                        <Button
                          type="button"
                          size="sm"
                          variant="outline"
                          className="h-8 border-[#3d3d3d] bg-[#252526] text-[#d4d4d4] hover:bg-[#323233] hover:text-white"
                          onClick={() => void handlePublishGeneratedWorldPackage()}
                          disabled={!canPublishGeneratedPackage}
                        >
                          {worldLabsPublishing ? (
                            <Loader2 className="animate-spin" />
                          ) : (
                            <UploadCloud />
                          )}
                          Publish locally
                        </Button>
                      </div>
                    </div>
                  </div>
                ) : null}
              </div>
            ) : null}
          </section>

          <div className="flex items-center gap-2">
            <input
              value={filterText}
              onChange={(event) => onFilterTextChange(event.target.value)}
              placeholder="Filter by package, version, runtime target..."
              className="h-9 flex-1 rounded-md border border-[#3d3d3d] bg-[#252526] px-3 text-sm text-[#e2e2e2] outline-none focus:border-[#5a5a5a]"
            />
            <Button
              type="button"
              variant="outline"
              className="h-9 border-[#3d3d3d] bg-[#252526] text-[#d4d4d4] hover:bg-[#323233] hover:text-white"
              onClick={onRefresh}
              disabled={loading || refreshGateUi.disabled}
              title={refreshGateUi.title}
            >
              {loading ? <Loader2 className="animate-spin" /> : <RefreshCw />}
              {loading ? "Refreshing..." : refreshGateUi.label}
            </Button>
          </div>

          <div className="max-h-[42vh] overflow-auto rounded-md border border-[#3d3d3d]">
            <table className="w-full text-left text-xs">
              <thead className="sticky top-0 bg-[#2a2a2a] text-[#b9b9b9]">
                <tr>
                  <th className="px-3 py-2 font-medium">Package</th>
                  <th className="px-3 py-2 font-medium">Version</th>
                  <th className="px-3 py-2 font-medium">Updated</th>
                  <th className="px-3 py-2 font-medium">Runtime Targets</th>
                  <th className="px-3 py-2 font-medium">Trust</th>
                  <th className="px-3 py-2 font-medium text-right">Action</th>
                </tr>
              </thead>
              <tbody>
                {filteredEntries.map((entry) => {
                  const key = `${entry.package_id}@${entry.latest_version}`;
                  const runtimeTargets = entry.runtime_targets;
                  const trustLevel = resolveTrustLevel(entry.trust_level);
                  const trustLabel = TRUST_LABEL_BY_LEVEL[trustLevel];
                  return (
                    <tr key={key} className="border-t border-[#333333]">
                      <td className="px-3 py-2">
                        <div className="font-medium text-[#f2f2f2]">{entry.package_id}</div>
                        <div className="text-[#9e9e9e]">{entry.title}</div>
                      </td>
                      <td className="px-3 py-2 text-[#e3e3e3]">{entry.latest_version}</td>
                      <td className="px-3 py-2 text-[#c5c5c5]">
                        {formatTimestamp(entry.updated_at)}
                      </td>
                      <td className="px-3 py-2 text-[#c5c5c5]">
                        {runtimeTargets.length > 0 ? runtimeTargets.join(", ") : "n/a"}
                      </td>
                      <td className="px-3 py-2">
                        <Badge
                          variant="outline"
                          className={TRUST_BADGE_CLASS_BY_LEVEL[trustLevel]}
                        >
                          {trustLabel}
                        </Badge>
                      </td>
                      <td className="px-3 py-2 text-right">
                        <Button
                          type="button"
                          size="sm"
                          variant="outline"
                          className="h-7 border-[#3d3d3d] bg-[#252526] text-[#d4d4d4] hover:bg-[#323233] hover:text-white"
                          onClick={() => onLoadPackage(entry)}
                          disabled={loadGateUi.disabled}
                          title={loadGateUi.title}
                        >
                          {loadGateUi.label}
                        </Button>
                      </td>
                    </tr>
                  );
                })}
                {filteredEntries.length === 0 && (
                  <tr>
                    <td colSpan={6} className="px-3 py-8 text-center text-[#9f9f9f]">
                      {loading ? "Loading world registry..." : "No world packages found"}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};
