export const BACKEND_PYTHON_CORE_SETUP = {
  dependencies: [
    'fastapi',
    'python-multipart',
    'uvicorn',
    'pydantic',
    'httpx',
    'httpx2',
    'huggingface_hub',
    'numpy==2.2.6',
    'pyarrow',
    'pytest',
    'yourdfpy',
  ],
  verifyImportScript: [
    'import importlib',
    'import importlib.metadata as metadata',
    'expected_versions = {"numpy": "2.2.6"}',
    'for package_name, expected_version in expected_versions.items():',
    '    actual_version = metadata.version(package_name)',
    '    assert actual_version == expected_version, f"{package_name}=={actual_version}, expected {expected_version}"',
    'for module_name in ("fastapi", "httpx", "httpx2", "multipart", "pyarrow", "uvicorn", "pytest", "yourdfpy"):',
    '    importlib.import_module(module_name)',
    'print("backend python core runtime ok")',
  ].join('\n'),
};
