export const OPERATOR_HELPER_PROVIDER_MANIFEST_PATH =
  "/.well-known/urdf-studio-teleop.json";
export const OPERATOR_HELPER_AUTHORIZED_PROVIDER_MANIFEST_PATH =
  "/manifest";
export const OPERATOR_HELPER_LOCAL_GATEWAY_PATH = "/robot-gateway";
export const OPERATOR_HELPER_LEASE_REQUEST_PATH = "/lease/request";
export const OPERATOR_HELPER_LEASE_RELEASE_PATH = "/lease/release";
export const OPERATOR_HELPER_TELEMETRY_STATE_PATH = "/telemetry/state";
export const OPERATOR_HELPER_ENV_CONFIG_PATH = "/config/env";
export const OPERATOR_HELPER_TWIST_PATH = "/control/twist";
export const OPERATOR_HELPER_STOP_PATH = "/control/stop";
export const OPERATOR_HELPER_ESTOP_PATH = "/control/estop";
export const OPERATOR_HELPER_JOINT_JOG_PATH = "/control/joint-jog";
export const OPERATOR_HELPER_JOINT_JOG_CAN_DRY_RUN_PATH =
  "/control/joint-jog/can-dry-run";
export const OPERATOR_HELPER_OPENARM_CALIBRATION_JOG_PATH =
  "/hardware/openarm/calibration/joint-jog";
export const OPERATOR_HELPER_LEADER_DETECTION_PATH =
  "/hardware/leaders";
export const OPERATOR_HELPER_LEADER_RELEASE_PATH =
  "/hardware/leaders/release";
export const OPERATOR_HELPER_LEADER_PATHS = {
  calibrationStart: "/hardware/leaders/calibration/start",
} as const;
export const OPERATOR_HELPER_FOLLOWER_RELEASE_PATH =
  "/hardware/follower/release";
export const OPERATOR_HELPER_FOLLOWER_PATHS = {
  calibrationStart: "/hardware/follower/calibration/start",
} as const;
export const OPERATOR_HELPER_LEROBOT_CALIBRATIONS_PATH =
  "/hardware/lerobot/calibrations";
export const OPERATOR_HELPER_LEROBOT_CALIBRATION_OPEN_PATH =
  "/hardware/lerobot/calibrations/open";
export const OPERATOR_HELPER_LEROBOT_CALIBRATION_SYNC_PATH =
  "/hardware/lerobot/calibrations/sync";
export const OPERATOR_HELPER_LEADER_STATE_PATH =
  "/hardware/leader-state";
export const OPERATOR_HELPER_POINT_CLOUD_PATH_SUFFIX = "/point-cloud";
export const OPERATOR_TELEOPERATION_MODE_SIMULATED = "simulated";
export const OPERATOR_TELEOPERATION_MODE_REAL_HARDWARE = "real_hardware";
export const OPERATOR_TELEOPERATION_MODE_STUDIO_KINEMATIC =
  "studio_kinematic";
export const OPERATOR_TELEOPERATION_MODE_LABELS = {
  [OPERATOR_TELEOPERATION_MODE_SIMULATED]: "Simulated gateway",
  [OPERATOR_TELEOPERATION_MODE_REAL_HARDWARE]: "Real hardware",
  [OPERATOR_TELEOPERATION_MODE_STUDIO_KINEMATIC]: "Studio kinematic",
} as const;
export const OPERATOR_TELEOP_ADAPTER_IDS = {
  lerobot: "lerobot",
  openArmNative: "openarm_native",
} as const;
export const OPERATOR_TELEOPERATION_MODE_FAKE_ADAPTER_ID = "fake_openarm";
export const OPERATOR_TELEOP_INPUT_SOURCE_IK_DRAG = "ik_drag";
export const OPERATOR_TELEOP_INPUT_SOURCE_IK_APPLY = "ik_apply";
export const OPERATOR_TELEOP_INPUT_SOURCE_JOINT_JOG = "joint_jog";
export const OPERATOR_TELEOP_INPUT_SOURCE_KEYBOARD = "keyboard";
export const OPERATOR_TELEOP_INPUT_SOURCE_ESTOP = "estop";
export const OPERATOR_TELEOP_PHYSICS_SOURCE_NONE = "none";
export const OPERATOR_TELEOP_PHYSICS_SOURCE_GATEWAY_PROXY = "gateway_proxy";
export const OPERATOR_TELEOP_PHYSICS_SOURCE_REAL_WORLD = "real_world";
export const OPERATOR_TELEOP_REPLAY_GUARANTEE_KINEMATIC = "kinematic";
export const OPERATOR_TELEOP_REPLAY_GUARANTEE_GATEWAY_DETERMINISTIC =
  "gateway_deterministic";
export const OPERATOR_HELPER_OPENARM_DEMO_ROBOT_NAME_TOKEN = "openarm";
export const OPERATOR_HELPER_OPENARM_FINGER_JOINT_NAME_TOKEN = "finger";
export const OPERATOR_ROBOT_MODEL_ID_DESCRIPTOR_SUFFIXES = [
  "bimanual",
  "follower",
  "gateway",
  "robot",
] as const;
export const OPERATOR_TELEOP_MS_PER_SECOND = 1_000;
export const OPERATOR_HELPER_POLL_INTERVAL_MS = 1_000;
export const OPERATOR_HELPER_POINT_CLOUD_POLL_INTERVAL_MS = 500;
export const OPERATOR_LEROBOT_CALIBRATION_FILE_EDIT_SESSION_ID_INCREMENT = 1;
export const OPERATOR_LEROBOT_CALIBRATION_FILE_SYNC_REVISION_INITIAL = 0;
export const OPERATOR_LEROBOT_CALIBRATION_FILE_SYNC_REVISION_INCREMENT = 1;
export const OPERATOR_LEROBOT_CALIBRATION_ZERO_POSITION_RAD = 0;
export const OPERATOR_LEROBOT_CALIBRATION_FILE_SYNC_INTERVAL_MS = 1_000;
export const OPERATOR_LEROBOT_CALIBRATION_FILE_EDIT_MOTION_WINDOW_MS = 2_000;
export const OPERATOR_LEROBOT_CALIBRATION_FILE_EDIT_MIN_MOTION_RAD = 0.002;
export const OPERATOR_LEADER_ASSIGNMENTS_STORAGE_KEY =
  "urdf-studio.leader.assignments.v1";
export const OPERATOR_PREVIOUS_OPENARM_LEADER_ASSIGNMENTS_STORAGE_KEY =
  "urdf-studio.openarm.leaderAssignments.v1";
export const OPERATOR_DEVICE_ROLE_ASSIGNMENTS_STORAGE_KEY =
  "urdf-studio.operator.deviceRoleAssignments.v1";
export const OPERATOR_TELEOP_PANEL_STATE_STORAGE = {
  key: "urdf-studio.operator.panelState.v1",
  version: 1,
} as const;
export const OPERATOR_LEADER_TELEMETRY_SOURCE_PREFIX = "leader:";
export const OPERATOR_LEADER_STATE_POLL_INTERVAL_MS = 50;
export const OPERATOR_LEADER_DETECTION_REFRESH_MS = 2_000;
export const OPERATOR_HELPER_TELEMETRY_POLLING = {
  intervalMs: 50,
} as const;
export const OPERATOR_HARDWARE_IK_COMMAND = {
  minDeltaRad: 1e-4,
  maxFollowerTelemetryAgeMs: OPERATOR_HELPER_TELEMETRY_POLLING.intervalMs * 10,
} as const;
export const OPERATOR_OPENARM_CALIBRATION_JOG = {
  stepRad: 0.002,
  testPauseMs: 250,
} as const;
export const OPERATOR_HELPER_COMMAND_SEQUENCE_INITIAL = 0;
export const OPERATOR_CONTROL_DATAGRAM_MONOTONIC_NS_PER_MS = 1_000_000;
export const OPERATOR_CONTROL_DATAGRAM_DEFAULT_ACK_TIMEOUT_MS = 200;
export const OPERATOR_CONTROL_TRANSPORT_TELEOP_CAPABILITY_VERIFY_PATH =
  "/collaboration/sessions/{sessionId}/capabilities/verify";
export const OPERATOR_CONTROL_TRANSPORT_TELEOP_CAPABILITY_REQUIRED_ROLE =
  "teleop_operator";
export const OPERATOR_CONTROL_TRANSPORT_TELEOP_CAPABILITY_TRANSPORT = "moq";
export const OPERATOR_CONTROL_TRANSPORT_MESSAGES = {
  capabilityRequired:
    "Teleop capability is required before sending control datagrams.",
  mismatch:
    "Control command transport mismatch. Use the active teleop control transport advertised by the robot gateway.",
  sessionMissing: "No active robot gateway session for teleop datagrams.",
} as const;
export const OPERATOR_HELPER_DEFAULT_OPERATOR_ID = "browser-operator";
export const OPERATOR_HELPER_TWIST_ZERO = 0;
export const OPERATOR_HELPER_DIRECTION_POSITIVE = 1;
export const OPERATOR_HELPER_DIRECTION_NEGATIVE = -1;
export const OPERATOR_HELPER_DEFAULT_LINEAR_SPEED_MPS = 0.2;
export const OPERATOR_HELPER_LINEAR_SPEED_MIN_MPS = 0.05;
export const OPERATOR_HELPER_LINEAR_SPEED_MAX_MPS = 1;
export const OPERATOR_HELPER_LINEAR_SPEED_STEP_MPS = 0.05;
export const OPERATOR_HELPER_DEFAULT_YAW_SPEED_RPS = 0.8;
export const OPERATOR_HELPER_YAW_SPEED_MIN_RPS = 0.1;
export const OPERATOR_HELPER_YAW_SPEED_MAX_RPS = 3.14;
export const OPERATOR_HELPER_YAW_SPEED_STEP_RPS = 0.1;
export const OPERATOR_HELPER_DEFAULT_JOINT_JOG_STEP_RAD = 0.01;
export const OPERATOR_HELPER_JOINT_JOG_STEP_MIN_RAD = 0.001;
export const OPERATOR_HELPER_JOINT_JOG_STEP_MAX_RAD = 0.05;
export const OPERATOR_HELPER_JOINT_JOG_STEP_RAD = 0.001;
export const OPERATOR_POINT_CLOUD_COORDINATE_COMPONENTS = 3;
export const OPERATOR_POINT_CLOUD_COLOR_COMPONENTS = 3;
export const OPERATOR_POINT_CLOUD_DEFAULT_POINT_SIZE_M = 0.012;
export const OPERATOR_POINT_CLOUD_LEVEL_CALIBRATION_MAX_SAMPLES = 4_096;
export const OPERATOR_POINT_CLOUD_LEVEL_CALIBRATION_HEIGHT_BIN_SIZE_M = 0.015;
export const OPERATOR_POINT_CLOUD_LEVEL_CALIBRATION_MIN_FLOOR_SAMPLES = 24;
export const OPERATOR_POINT_CLOUD_LEVEL_CALIBRATION_FLOOR_BIN_WINDOW = 2;
export const OPERATOR_POINT_CLOUD_LEVEL_CALIBRATION_NO_LOWER_BIN_WINDOW = 0;
export const OPERATOR_POINT_CLOUD_LEVEL_CALIBRATION_MIN_DETERMINANT = 1e-9;
export const OPERATOR_POINT_CLOUD_LEVEL_CALIBRATION_MAX_CORRECTION_RAD =
  Math.PI / 12;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_DURATION_MS = 5_000;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_SAMPLE_INTERVAL_MS = 250;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_MAX_ACCUMULATED_SAMPLES = 16_384;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_PLANE_COLOR = "#2dd4bf";
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_PLANE_OPACITY = 0.34;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_PLANE_RENDER_ORDER = 8;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_PLANE_POLYGON_OFFSET_FACTOR = -1;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_PLANE_POLYGON_OFFSET_UNITS = -1;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_PLANE_MIN_SIZE_M = 0.18;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_PLANE_PADDING_M = 0.08;
export const OPERATOR_POINT_CLOUD_AUTOCALIBRATION_PLANE_MIN_AXIS_LENGTH = 1e-6;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_MAX_SURFACES = 4;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_MAX_SAMPLES_PER_FRAME = 65_536;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_MIN_SURFACE_SAMPLES = 96;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_MIN_AREA_M2 = 0.02;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_THICKNESS_M = 0.025;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_FOOTPRINT_PADDING_M = 0.03;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_HALF_EXTENT_FACTOR = 0.5;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_LABEL_INDEX_OFFSET = 1;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_COLOR_MAX = 255;
export const OPERATOR_POINT_CLOUD_SCENE_MESH_DEFAULT_COLOR = "#ffffff";
export const OPERATOR_POINT_CLOUD_SURFACE_YAW_COVARIANCE_CROSS_FACTOR = 2;
export const OPERATOR_POINT_CLOUD_SURFACE_YAW_HALF_ANGLE_FACTOR = 0.5;
export const OPERATOR_POINT_CLOUD_SURFACE_YAW_FALLBACK_RAD = 0;
export const OPERATOR_POINT_CLOUD_SURFACE_PLANE_AXIS_Z = 0;
export const OPERATOR_POINT_CLOUD_SURFACE_PLANE_UP = [0, 0, 1] as const;
export const OPERATOR_POINT_CLOUD_SURFACE_PLANE_FALLBACK_AXIS = [0, 1, 0] as const;
export const OPERATOR_POINT_CLOUD_HF_X_AXIS_IN_URDF_Z_UP = [0, 1, 0] as const;
export const OPERATOR_POINT_CLOUD_HF_Y_AXIS_IN_URDF_Z_UP = [0, 0, 1] as const;
export const OPERATOR_POINT_CLOUD_HF_Z_AXIS_IN_URDF_Z_UP = [1, 0, 0] as const;
export const OPERATOR_POINT_CLOUD_GRAVITY_MIN_NORM = 0.5;
export const OPERATOR_POINT_CLOUD_HF_GRAVITY_TARGET_Y = [0, -1, 0] as const;
export const OPERATOR_POINT_CLOUD_HF_GRAVITY_YAW_AXIS = [0, 1, 0] as const;
export const OPERATOR_LIVE_CAMERA_SINGLE_FRAME_COUNT = 1;
export const OPERATOR_LIVE_CAMERA_GRID_TWO_COLUMN_MIN_COUNT = 2;
export const OPERATOR_LIVE_CAMERA_CANVAS_STREAM_FPS = 10;
export const OPERATOR_LIVE_CAMERA_RGBA_COMPONENTS = 4;
export const OPERATOR_LIVE_CAMERA_RGB_COMPONENTS = 3;
export const OPERATOR_LIVE_CAMERA_RED_CHANNEL_OFFSET = 0;
export const OPERATOR_LIVE_CAMERA_GREEN_CHANNEL_OFFSET = 1;
export const OPERATOR_LIVE_CAMERA_BLUE_CHANNEL_OFFSET = 2;
export const OPERATOR_LIVE_CAMERA_ALPHA_CHANNEL_OFFSET = 3;
export const OPERATOR_LIVE_CAMERA_COLOR_MAX = 255;
export const OPERATOR_LIVE_CAMERA_ALPHA_CHANNEL_VALUE = 255;
export const OPERATOR_LIVE_JOINT_TELEMETRY_PRECISION = 3;

export const OPERATOR_HELPER_STOP_TWIST = {
  x: OPERATOR_HELPER_TWIST_ZERO,
  y: OPERATOR_HELPER_TWIST_ZERO,
  omega: OPERATOR_HELPER_TWIST_ZERO,
} as const;
