export const ROBOT_FRAME_LINTER_RPY_EPSILON_RAD = 1e-2;
export const ROBOT_FRAME_LINTER_CANONICAL_COMPENSATION_RATIO_MAX = 0.2;
export const ROBOT_FRAME_LINTER_UNSAFE_COMPENSATION_RATIO_MIN = 0.45;
export const ROBOT_FRAME_LINTER_UNSAFE_JOINT_COMPENSATION_RATIO_MIN = 0.35;
export const ROBOT_FRAME_LINTER_WHEEL_CONFLICT_DOMINANCE_MIN = 0.6;
