export const VIEWER_CAMERA_CONTROL_PARAMS = {
  defaultFocusCenter: [0, 0, 0],
  viewDirectionOffsets: {
    front: [1, 0, 0],
    back: [-1, 0, 0],
    left: [0, -1, 0],
    right: [0, 1, 0],
    top: [0, 0, 1],
    bottom: [0, 0, -1],
  },
  setViewDistanceScale: 2.6,
  setViewMinDistance: 1.5,
  cameraLookAtDistance: 1.0,
  cameraMinFocusRadius: 0.25,
  cameraMinNearPlane: 0.01,
  cameraNearPlaneScale: 0.02,
  cameraMinFarPlane: 20,
  cameraFarPlaneScale: 40,
  cameraFarToNearRatio: 50,
  fitMinFocusRadius: 0.25,
  fitMinHalfFov: 0.01,
  fitDistanceSineScale: 1.6,
  fitDistanceMinFallback: 0.75,
  fitDistancePadding: 1.15,
  fitBoundsDiameterScale: 2,
  fitDirectionEpsilon: 0.001,
  fitDefaultDirection: [1, 1, 0.5],
  fitMinDistanceScale: 0.05,
  fitMinDistanceFallback: 0.03,
  fitMaxDistanceScale: 80,
  fitMaxToMinDistanceRatio: 30,
  fitMaxDistanceFallback: 12,
  globalFallbackAspect: 16 / 9,
  globalFallbackFovDeg: 50,
} as const;
