from __future__ import annotations

from backend.world_bridge.params import (
    DEFAULT_SCENARIO_DURATION_MS,
    WORLDD_DEFAULT_HOST,
    WORLDD_DEFAULT_PORT,
    WORLDD_DEFAULT_TIMEOUT_MS,
)

CONFORMANCE_ROBOT_NAME = "conformance-bot"
CONFORMANCE_CAMERA_IDS = ["base_cam", "wrist_cam"]
CONFORMANCE_JOINT_POSITIONS_RAD = {
    "joint_1": 0.25,
    "joint_2": -0.5,
}
CONFORMANCE_SCENARIO_TIME_MS = 900
CONFORMANCE_SCENARIO_DURATION_MS = DEFAULT_SCENARIO_DURATION_MS
CONFORMANCE_COMMAND_SOURCE = "conformance-suite"
CONFORMANCE_COMMAND_SEQUENCE_ID = 7
CONFORMANCE_WORLDD_HOST = WORLDD_DEFAULT_HOST
CONFORMANCE_WORLDD_PORT = WORLDD_DEFAULT_PORT
CONFORMANCE_WORLDD_TIMEOUT_MS = WORLDD_DEFAULT_TIMEOUT_MS
