from __future__ import annotations

# Runtime identity
WORLD_BRIDGE_SERVICE_NAME = "urdf-world-bridge"
WORLD_BRIDGE_RUNTIME_MODE = "python-control-plane"

# worldd proxy defaults
WORLDD_DEFAULT_HOST = "127.0.0.1"
WORLDD_DEFAULT_PORT = 8088
WORLDD_DEFAULT_TIMEOUT_MS = 400
WORLDD_SERVICE_NAME = "worldd-world-bridge"
WORLDD_RUNTIME_MODE = "rust-data-plane"

# Session id / event id formatting
SESSION_ID_PREFIX = "wbs"
SESSION_ID_HEX_LENGTH = 12
EVENT_ID_PREFIX = "evt"
TRANSITION_ID_PREFIX = "trn"
TRANSITION_CONTRACT_VERSION = "1.0.0"

# Scenario timeline limits
DEFAULT_SCENARIO_DURATION_MS = 12_000
MIN_SCENARIO_DURATION_MS = 1_000
MAX_SCENARIO_DURATION_MS = 600_000

# Session payload limits
MAX_CAMERAS_PER_SESSION = 32
MAX_JOINTS_PER_COMMAND = 256
MAX_EVENTS_PER_SESSION = 512
MAX_TRANSITIONS_PER_SESSION = 512
MAX_ACTIVE_SESSIONS = 128
MAX_TRACKED_EXTERNAL_SESSIONS = 512
WORLD_BRIDGE_SESSION_IDLE_TTL_MS = 7_200_000

# Monotonic command sequencing
COMMAND_SEQUENCE_START = 1
COMMAND_SEQUENCE_STEP = 1
