from __future__ import annotations

# Global target tightening factor.
# 0.50 means every tracked latency budget must be at least 2x better
# than the previous baseline budget.
PERF_TARGET_REDUCTION_FACTOR = 0.50

# Benchmark defaults
PERF_DEFAULT_SESSION_COUNT = 8
PERF_DEFAULT_COMMANDS_PER_SESSION = 2_000
PERF_DEFAULT_JOINTS_PER_COMMAND = 6
PERF_DEFAULT_SCENARIO_UPDATES_PER_SESSION = 200
PERF_LIST_SESSIONS_MEASURE_ITERATIONS = 20
PERF_STARTUP_APP_MEASURE_ITERATIONS = 5
PERF_STARTUP_RUNTIME_MEASURE_ITERATIONS = 20
PERF_OPERATION_MAX_RETRIES = 1

# Deterministic benchmark setup values
PERF_BENCHMARK_ROBOT_NAME = "perf-bot"
PERF_BENCHMARK_SCENARIO_DURATION_MS = 12_000
PERF_BENCHMARK_COMMAND_SOURCE = "perf-suite"
PERF_SEQUENCE_START = 1
PERF_SEQUENCE_STEP = 1

# Baseline guardrails (before tightening).
PERF_BASELINE_COMMAND_P95_MS = 2.0
PERF_BASELINE_COMMAND_P99_MS = 4.0
PERF_BASELINE_SCENARIO_UPDATE_P95_MS = 1.0
PERF_BASELINE_GET_SESSION_P95_MS = 1.0
PERF_BASELINE_CREATE_SESSION_P95_MS = 1.0
PERF_BASELINE_LIST_SESSIONS_P95_MS = 2.0
PERF_BASELINE_STATUS_PAYLOAD_BYTES = 4_096
PERF_BASELINE_CREATE_SESSION_PAYLOAD_BYTES = 65_536
PERF_BASELINE_GET_SESSION_PAYLOAD_BYTES = 262_144
PERF_BASELINE_LIST_SESSIONS_PAYLOAD_BYTES = 2_000_000
PERF_BASELINE_PYTHON_PEAK_ALLOCATED_MIB = 128.0
# Full FastAPI app construction registers all backend routes. Keep this separate from
# the data-plane latency budgets so world-bridge payload regressions stay visible.
PERF_BASELINE_APP_STARTUP_P95_MS = 140.0
PERF_BASELINE_RUNTIME_STARTUP_P95_MS = 4.0
PERF_BASELINE_ERROR_RATE = 0.02
PERF_BASELINE_RETRY_RATE = 0.02
PERF_BASELINE_MAX_FAILED_OPERATIONS = 2
PERF_BASELINE_MAX_RETRIES = 2

# Tightened guardrails (all reduced by PERF_TARGET_REDUCTION_FACTOR).
PERF_TARGET_COMMAND_P95_MS = PERF_BASELINE_COMMAND_P95_MS * PERF_TARGET_REDUCTION_FACTOR
PERF_TARGET_COMMAND_P99_MS = PERF_BASELINE_COMMAND_P99_MS * PERF_TARGET_REDUCTION_FACTOR
PERF_TARGET_SCENARIO_UPDATE_P95_MS = (
    PERF_BASELINE_SCENARIO_UPDATE_P95_MS * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_GET_SESSION_P95_MS = PERF_BASELINE_GET_SESSION_P95_MS * PERF_TARGET_REDUCTION_FACTOR
PERF_TARGET_CREATE_SESSION_P95_MS = (
    PERF_BASELINE_CREATE_SESSION_P95_MS * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_LIST_SESSIONS_P95_MS = (
    PERF_BASELINE_LIST_SESSIONS_P95_MS * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_STATUS_PAYLOAD_BYTES = int(
    PERF_BASELINE_STATUS_PAYLOAD_BYTES * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_CREATE_SESSION_PAYLOAD_BYTES = int(
    PERF_BASELINE_CREATE_SESSION_PAYLOAD_BYTES * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_GET_SESSION_PAYLOAD_BYTES = int(
    PERF_BASELINE_GET_SESSION_PAYLOAD_BYTES * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_LIST_SESSIONS_PAYLOAD_BYTES = int(
    PERF_BASELINE_LIST_SESSIONS_PAYLOAD_BYTES * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_PYTHON_PEAK_ALLOCATED_MIB = (
    PERF_BASELINE_PYTHON_PEAK_ALLOCATED_MIB * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_APP_STARTUP_P95_MS = (
    PERF_BASELINE_APP_STARTUP_P95_MS * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_RUNTIME_STARTUP_P95_MS = (
    PERF_BASELINE_RUNTIME_STARTUP_P95_MS * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_ERROR_RATE = PERF_BASELINE_ERROR_RATE * PERF_TARGET_REDUCTION_FACTOR
PERF_TARGET_RETRY_RATE = PERF_BASELINE_RETRY_RATE * PERF_TARGET_REDUCTION_FACTOR
PERF_TARGET_MAX_FAILED_OPERATIONS = int(
    PERF_BASELINE_MAX_FAILED_OPERATIONS * PERF_TARGET_REDUCTION_FACTOR
)
PERF_TARGET_MAX_RETRIES = int(PERF_BASELINE_MAX_RETRIES * PERF_TARGET_REDUCTION_FACTOR)
