from __future__ import annotations

# Watch-level gates: minimum telemetry to justify continued investment.
READINESS_MIN_TRANSITIONS_FOR_WATCH = 200
READINESS_MIN_UNIQUE_ROBOTS_FOR_WATCH = 1
READINESS_MIN_UNIQUE_PLANNERS_FOR_WATCH = 1

# Go-level gates: minimum telemetry to justify a full PWMI/PWMP migration.
READINESS_MIN_TRANSITIONS_FOR_GO = 2_000
READINESS_MIN_UNIQUE_ROBOTS_FOR_GO = 2
READINESS_MIN_UNIQUE_PLANNERS_FOR_GO = 2
READINESS_MIN_UNIQUE_TASKS_FOR_GO = 2
READINESS_MIN_UNIQUE_ADAPTERS_FOR_GO = 1
READINESS_MIN_COUNTERFACTUAL_TRANSITIONS_FOR_GO = 200
READINESS_MIN_LIVE_ROLLOUT_TRANSITIONS_FOR_GO = 200
