export const ROVER_APPROACH_DETOUR_CONFIG = {
  segmentLengthEpsilonSq: 1e-8,
  obstacleRadiusLowerBoundM: 0.01,
  waypointExtraOffsetM: 0.05,
  minDetourImprovementM: 0.005,
  waypointPlanStopDistanceM: 0,
  pathClearancePaddingM: 0.04,
  objectContactPathClearancePaddingM: 0.06,
  baseRadiusFallbackM: 0.18,
  timeoutBonusMs: 3500,
  finalLegMinBudgetMs: 3000,
  timeoutLinearSpeedUtilization: 0.45,
  timeoutAngularSpeedUtilization: 0.4,
  timeoutPerSegmentMs: 900,
  timeoutPerWaypointMs: 700,
  timeoutMinLinearSpeedMps: 0.08,
  timeoutMinAngularSpeedRadps: 0.3,
} as const;
