export const ROVER_APPROACH_NAVIGATION_CONFIG = {
  gridCellSizeM: 0.12,
  gridBoundsPaddingM: 0.24,
  gridBoundsMinSpanM: 2.4,
  gridBoundsGoalDistanceScale: 0.75,
  maxGridCellsPerAxis: 96,
  maxGridCellCount: 4096,
  occupancyCacheKeyPrecisionDigits: 4,
  occupancyCacheMaxEntries: 24,
  blockedCellRadiusPaddingM: 0.05,
  lineOfSightClearancePaddingM: 0.02,
  lineOfSightSampleStepMinM: 0.04,
  minWaypointSpacingM: 0.18,
  turnPenaltyWeight: 0.18,
  waypointPenaltyWeight: 0.08,
  nearObstaclePenaltyDistanceM: 0.3,
  nearObstaclePenaltyWeight: 0.12,
  narrowPassagePenaltyDistanceM: 0.12,
  narrowPassagePenaltyWeight: 0.55,
  visibilityNodePaddingM: 0.04,
  visibilityCornerBypassOffsetM: 0.16,
  visibilityClearancePreferenceWeight: 0.6,
  visibilityEdgeRejectClearancePaddingM: 0.06,
  visibilityHeadingPenaltyWeight: 0.1,
  robotFootprintLengthFallbackTrackWidthRatio: 1.5,
  timeoutBonusPerWaypointMs: 2500,
  maxTimeoutBonusMs: 10000,
} as const;
