export const ROVER_APPROACH_CONFIG = {
  planarDirectionLengthEpsilonSq: 1e-8,
  rearTargetDotThreshold: -0.12,
  yawTriggerRad: Math.PI / 18,
  yawToleranceRad: Math.PI / 90,
  initialRotateThresholdRad: Math.PI / 6,
  yawPhaseRotateEnterRad: Math.PI / 4,
  yawPhaseRotateExitRad: Math.PI / 9,
  yawRotateInPlaceThresholdRad: Math.PI / 6,
  yawTranslateCommandScale: 0.75,
  yawTranslateAngularSpeedMaxRadps: 1.2,
  yawTranslateSlowdownStartRad: Math.PI / 6,
  yawTranslateMinSpeedScale: 0.5,
  distanceToleranceM: 0.02,
  objectContactSurfaceStandoffM: 0.012,
  objectContactDistanceToleranceM: 0.008,
  reachGapTriggerM: 0.08,
  minStopDistanceM: 0.08,
  maxStopDistanceM: 0.6,
  fallbackStopDistanceM: 0.16,
  stopDistanceReachRatio: 0.22,
  stopDistanceStandOffM: 0.04,
  translationGain: 1.9,
  rotationGain: 2.6,
  maxLinearSpeedMps: 0.9,
  maxAngularSpeedRadps: 1.9,
  maxLinearAccelMps2: 1.8,
  maxAngularAccelRadps2: 4.2,
  minDtSec: 1 / 240,
  maxDtSec: 1 / 30,
  speedDtDenominatorEpsilonSec: 1e-6,
  appliedTravelEpsilon: 1e-8,
  wheelRadiusLowerBoundM: 0.01,
  timeoutMs: 9000,
  settleFrames: 3,
  progressPublishIntervalMs: 80,
  armResetSettleTimeoutMs: 450,
  armResetSettleFrames: 2,
  armResetJointToleranceRad: 0.03,
} as const;
