// Studio-local boundary over the public i-love-urdf package.
// Web code should import from here instead of reaching into i-love-urdf directly.

// Explicit named re-exports from i-love-urdf (CJS package).
// `export * from "cjs"` loses named exports in Vite dev mode; explicit exports work correctly.
export {
  addCollisionToLink,
  addInertialToLink,
  analyzeUrdf,
  analyzeUrdfDocument,
  autoFitCollisionGeometry,
  buildAssemblyUrdf,
  buildPackageRootsFromRepositoryFiles,
  buildRepositoryFileEntriesFromPaths,
  buildRobotOrientationCard,
  buildRobotStructureLabels,
  buildXacroExpandRequestPayload,
  buildXacroFilenameCandidates,
  convertURDFToMJCF,
  convertURDFToXacro,
  createAssemblySpec,
  createXacroFilePayloadFromText,
  extractPackageNameFromPackageXml,
  healthCheckUrdf,
  inspectRepositoryCandidates,
  isSupportedMeshExtension,
  isSupportedMeshResource,
  isUrdfXacroPath,
  isXacroPath,
  isXacroSupportPath,
  meshExtensionsDisplay,
  normalizeExpandedUrdfPath,
  normalizeRobot,
  parseXacroExpandResponsePayload,
  removeCollisionFromLink,
  removeInertialFromLink,
  removeJointsFromUrdf,
  removeVisualFromLink,
  renameJointInUrdf,
  renameLinkInUrdf,
  resolveDirectionCueFromDirectionSamples,
  resolvePrincipalAxesFromDirectionSamples,
  resolveRepositoryFileReference,
  resolveRepositoryXacroTargetPath,
  resolveUpCueFromDirectionSamples,
  sanitizeUrdfName,
  setJointAxisInUrdf,
  updateCollisionInLink,
  updateInertialInLink,
  updateJointLimitsInUrdf,
  updateJointLinksInUrdf,
  updateJointOriginInUrdf,
  updateJointTypeInUrdf,
  updateJointVelocityInUrdf,
  updateMaterialColorInUrdf,
  updateVisualInLink,
  validateAssemblySpec,
  validateJointLinkReassignment,
} from "i-love-urdf";
export type {
  AxisSpec,
  CollisionData,
  CollisionEntry,
  InertialEntry,
  LinkGeometryParams,
  LinkGeometryType,
  LinkInertiaTensor,
  LinkOrigin,
  OrientationAxis,
  ParsedSensor,
  RepositoryFileEntry,
  RobotOrientationCard,
  RobotStructureLabels,
  UrdfAnalysis,
  VisualData,
} from "i-love-urdf";

export {
  buildPackageRootsFromMeshBlobMap,
  getJointLinks,
  normalizeMeshPathForMatch,
  parseJointLimitsFromURDF,
  parseMeshReference,
  parseUrdfDocument,
  parseURDF,
  prettyPrintURDF,
  resolveMeshCandidates,
  resolveMeshBlobFromReference,
  serializeUrdfDocument,
  type JointAxisInfo,
  type JointAxisMap,
  type JointHierarchyNode,
  type JointLimitInfo,
  type JointLimits,
  type LinkData,
  type MeshBounds,
  type OriginData,
} from "./urdfBrowser";
